const URL=Deno.env.get('SUPABASE_URL')!; const KEY=Deno.env.get('SUPABASE_SERVICE_ROLE_KEY')!; const enc=new TextEncoder();
function cors(req:Request){const o=req.headers.get('origin')||'';const ok=o==='https://umar-vai.github.io'||o.startsWith('http://localhost:');return {'Access-Control-Allow-Origin':ok?o:'https://umar-vai.github.io','Access-Control-Allow-Headers':'authorization,content-type,apikey','Access-Control-Allow-Methods':'POST,OPTIONS','Vary':'Origin'};}
function json(req:Request,d:any,s=200){return new Response(JSON.stringify(d),{status:s,headers:{...cors(req),'content-type':'application/json'}})}
async function sha(v:string){const b=await crypto.subtle.digest('SHA-256',enc.encode(v));return [...new Uint8Array(b)].map(x=>x.toString(16).padStart(2,'0')).join('')}
async function db(path:string,opt:any={}){const h={apikey:KEY,Authorization:'Bearer '+KEY,'content-type':'application/json',...(opt.headers||{})};const r=await fetch(URL+'/rest/v1/'+path,{...opt,headers:h});const t=await r.text();let d:any=null;try{d=t?JSON.parse(t):null}catch{d=t}if(!r.ok)throw new Error(typeof d==='object'?(d.message||d.details||'Database error'):String(d));return d}
async function user(req:Request){const auth=req.headers.get('authorization')||'';if(!auth.startsWith('Bearer '))throw new Error('Authentication required');const r=await fetch(URL+'/auth/v1/user',{headers:{apikey:KEY,Authorization:auth}});if(!r.ok)throw new Error('Invalid session');const u=await r.json();const p=await db('profiles?select=id,role&id=eq.'+encodeURIComponent(u.id)+'&limit=1');if(!p?.[0]||p[0].role!=='admin')throw new Error('Admin access required');return u}
function token(){const b=new Uint8Array(32);crypto.getRandomValues(b);return btoa(String.fromCharCode(...b)).replace(/\+/g,'-').replace(/\//g,'_').replace(/=+$/,'')}
Deno.serve(async(req)=>{try{if(req.method==='OPTIONS')return new Response('',{headers:cors(req)});if(req.method!=='POST')return json(req,{error:'POST required'},405);const u=await user(req);const body=await req.json().catch(()=>({}));const action=String(body.action||'list');
 if(action==='list'){const devices=await db('support_bridge_devices?select=id,label,enabled,created_at,last_seen_at&order=created_at.desc');const tx=await db('support_admin_recent?select=id,provider,sender_last4,amount,trx_id,received_at,claimed_at,claimed_by_name&order=received_at.desc&limit=40');const wallets=await db('support_wallets?select=user_id,balance,updated_at&order=updated_at.desc&limit=2000');const profiles=await db('profiles?select=id,display_name,email,balance&order=created_at.desc&limit=2000');const wm=new Map((wallets||[]).map((w:any)=>[w.user_id,w]));const merged=(profiles||[]).map((p:any)=>{const w:any=wm.get(p.id)||{};return {user_id:p.id,balance:Number(w.balance||0),updated_at:w.updated_at||null,display_name:p.display_name||p.email||'User',email:p.email||'',draw_credits:Number(p.balance||0)}});return json(req,{devices,transactions:tx,wallets:merged});}
 if(action==='create'){const label=String(body.label||'Android Phone').trim().slice(0,80);if(!label)return json(req,{error:'Device label required'},400);const plain=token();const hash=await sha(plain);const rows=await db('support_bridge_devices',{method:'POST',headers:{Prefer:'return=representation'},body:JSON.stringify({label,token_hash:hash,created_by:u.id})});return json(req,{ok:true,device:rows?.[0],deviceToken:plain});}
 if(action==='revoke'){const id=String(body.id||'');if(!id)return json(req,{error:'Device id required'},400);await db('support_bridge_devices?id=eq.'+encodeURIComponent(id),{method:'PATCH',body:JSON.stringify({enabled:false})});return json(req,{ok:true});}
 if(action==='enable'){const id=String(body.id||'');if(!id)return json(req,{error:'Device id required'},400);await db('support_bridge_devices?id=eq.'+encodeURIComponent(id),{method:'PATCH',body:JSON.stringify({enabled:true})});return json(req,{ok:true});}
 if(action==='adjust_support'){const userId=String(body.userId||'');const value=Number(body.newBalance);const note=String(body.note||'Admin live adjustment').trim().slice(0,300);if(!/^[0-9a-f-]{36}$/i.test(userId))return json(req,{error:'Valid user id required'},400);if(!Number.isFinite(value)||value<0||value>100000000)return json(req,{error:'Support Points must be between 0 and 100,000,000'},400);const oldRows=await db('support_wallets?select=balance&user_id=eq.'+encodeURIComponent(userId)+'&limit=1');const previous=Number(oldRows?.[0]?.balance||0);await db('support_wallets?on_conflict=user_id',{method:'POST',headers:{Prefer:'resolution=merge-duplicates,return=representation'},body:JSON.stringify({user_id:userId,balance:value,updated_at:new Date().toISOString()})});await db('support_point_adjustments',{method:'POST',body:JSON.stringify({user_id:userId,previous_balance:previous,new_balance:value,actor_user_id:u.id,note})});return json(req,{ok:true,userId,previousBalance:previous,newBalance:value});}
 return json(req,{error:'Unknown action'},400);
 }catch(e){const m=e instanceof Error?e.message:String(e);return json(req,{error:m},/Admin|Authentication|Invalid session/.test(m)?403:500)}});