import { createClient } from 'https://cdn.jsdelivr.net/npm/@supabase/supabase-js@2.117.2/+esm';
import { SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, APP_URL, BACKEND_READY } from './config.js';

const supabase = BACKEND_READY ? createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, { auth: { persistSession: true, detectSessionInUrl: true, autoRefreshToken: true } }) : null;
const $ = id => document.getElementById(id);
const slug = new URLSearchParams(location.search).get('e');
const S = { event: null, session: null, profile: null, white: [], bonus: null, tickets: [] };

function credits(v){return `${Number(v||0).toLocaleString()} credits`}
function fmt(v){return v?new Date(v).toLocaleString([], {month:'short',day:'numeric',hour:'numeric',minute:'2-digit'}):'—'}
function esc(v){return String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function statusFor(e){if(e.status==='completed')return'COMPLETED';if(e.status==='cancelled')return'CANCELLED';const n=Date.now();if(n<new Date(e.opens_at).getTime())return'UPCOMING';if(n<new Date(e.cutoff_at).getTime())return'OPEN';if(n<new Date(e.draw_at).getTime())return'LOCKED';return'AWAITING DRAW'}
function notice(m,type=''){$('notice').textContent=m;$('notice').className=`notice${type?' '+type:''}`}
function randomInt(max){const lim=Math.floor(0x100000000/max)*max,b=new Uint32Array(1);do crypto.getRandomValues(b);while(b[0]>=lim);return b[0]%max}
function uniqueRandom(count,max){const s=new Set();while(s.size<count)s.add(randomInt(max)+1);return [...s].sort((a,b)=>a-b)}

async function login(){if(!supabase)return;localStorage.setItem('draw01_post_login_event',slug||'');const {error}=await supabase.auth.signInWithOAuth({provider:'google',options:{redirectTo:APP_URL}});if(error)notice(error.message,'error')}
async function logout(){if(!supabase)return;await supabase.auth.signOut();S.session=null;S.profile=null;renderAuth();await loadMyTickets()}

function renderAuth(){const user=S.session?.user;$('loginBtn').hidden=!!user;$('accountCard').hidden=!user;$('balancePill').hidden=!user;if(!user){$('balanceValue').textContent='0 credits';return}const m=user.user_metadata||{};$('name').textContent=m.full_name||m.name||user.email?.split('@')[0]||'Player';$('email').textContent=user.email||'';$('avatar').src=m.avatar_url||`https://ui-avatars.com/api/?name=${encodeURIComponent($('name').textContent)}`;$('balanceValue').textContent=credits(S.profile?.balance||0)}

function buildPicker(){const e=S.event,w=$('whiteGrid'),b=$('bonusGrid');w.replaceChildren();b.replaceChildren();for(let n=1;n<=e.white_ball_max;n++){const x=document.createElement('button');x.type='button';x.className='num';x.textContent=n;x.dataset.n=n;x.onclick=()=>toggleWhite(n);w.appendChild(x)}if(e.bonus_ball_enabled){$('bonusBlock').hidden=false;for(let n=1;n<=e.bonus_ball_max;n++){const x=document.createElement('button');x.type='button';x.className='num';x.textContent=n;x.dataset.n=n;x.onclick=()=>toggleBonus(n);b.appendChild(x)}}else $('bonusBlock').hidden=true;syncPicker()}
function toggleWhite(n){const i=S.white.indexOf(n);if(i>=0)S.white.splice(i,1);else if(S.white.length<S.event.white_ball_count)S.white.push(n);S.white.sort((a,b)=>a-b);syncPicker()}
function toggleBonus(n){S.bonus=S.bonus===n?null:n;syncPicker()}
function syncPicker(){const e=S.event;[...$('whiteGrid').children].forEach(x=>{const n=Number(x.dataset.n),sel=S.white.includes(n);x.classList.toggle('selected',sel);x.classList.toggle('locked',S.white.length>=e.white_ball_count&&!sel)});[...$('bonusGrid').children].forEach(x=>x.classList.toggle('selected',S.bonus===Number(x.dataset.n)));$('whiteCount').textContent=`${S.white.length} / ${e.white_ball_count}`;$('bonusCount').textContent=`${S.bonus?1:0} / 1`;renderPreview();const ready=S.white.length===e.white_ball_count&&(!e.bonus_ball_enabled||S.bonus);const open=statusFor(e)==='OPEN';$('buyBtn').disabled=!ready||!open;$('buyHint').textContent=!open?'Ticket sales are not currently open.':ready?(S.session?'Ready to confirm with your balance.':'Login will be requested when you confirm.'):'Choose all required numbers.'}
function renderPreview(){const e=S.event,root=$('ticketPreview');root.replaceChildren();for(let i=0;i<e.white_ball_count;i++){const x=document.createElement('span');x.className='preview-ball'+(S.white[i]?'':' empty');x.textContent=S.white[i]?String(S.white[i]).padStart(2,'0'):'—';root.appendChild(x)}if(e.bonus_ball_enabled){const p=document.createElement('span');p.className='preview-ball bonus'+(S.bonus?'':' empty');p.textContent=S.bonus?String(S.bonus).padStart(2,'0'):'B';root.appendChild(p)}}
function quickPick(){S.white=uniqueRandom(S.event.white_ball_count,S.event.white_ball_max);S.bonus=S.event.bonus_ball_enabled?randomInt(S.event.bonus_ball_max)+1:null;syncPicker()}

async function loadProfile(){if(!S.session?.user){S.profile=null;renderAuth();return}const {data,error}=await supabase.from('profiles').select('id,display_name,email,avatar_url,balance,role').eq('id',S.session.user.id).maybeSingle();if(!error)S.profile=data;renderAuth()}
async function loadMyTickets(){const root=$('myTickets');if(!S.session?.user){S.tickets=[];root.innerHTML='<p class="muted">Sign in to see your entries.</p>';$('ticketUsage').textContent=`0 / ${S.event?.max_tickets_per_user||0}`;return}const {data,error}=await supabase.from('event_tickets').select('id,white_numbers,bonus_ball,price_paid,is_winner,prize_awarded,created_at').eq('event_id',S.event.id).order('created_at',{ascending:false});if(error){root.innerHTML=`<p class="muted">${esc(error.message)}</p>`;return}S.tickets=data||[];$('ticketUsage').textContent=`${S.tickets.length} / ${S.event.max_tickets_per_user}`;root.replaceChildren();if(!S.tickets.length){root.innerHTML='<p class="muted">No entries for this event yet.</p>';return}S.tickets.forEach((t,i)=>{const el=document.createElement('div');el.className='entry';el.innerHTML=`<strong>Ticket ${S.tickets.length-i}${t.is_winner?' · <span class="winner">WINNER</span>':''}</strong><small>${t.white_numbers.map(n=>String(n).padStart(2,'0')).join('  ')}${t.bonus_ball?` + ${String(t.bonus_ball).padStart(2,'0')}`:''} · ${credits(t.price_paid)}${Number(t.prize_awarded)>0?` · Prize ${credits(t.prize_awarded)}`:''}</small>`;root.appendChild(el)})}

async function buy(){if(!S.session?.user){await login();return}if(S.tickets.length>=S.event.max_tickets_per_user){notice('You have reached this event’s ticket limit.','error');return}const btn=$('buyBtn');btn.disabled=true;btn.textContent='Confirming…';const {data,error}=await supabase.rpc('purchase_event_ticket',{p_event_id:S.event.id,p_white_numbers:S.white,p_bonus_ball:S.event.bonus_ball_enabled?S.bonus:null});btn.textContent='Confirm ticket';if(error){notice(error.message,'error');syncPicker();return}const row=Array.isArray(data)?data[0]:data;if(row?.new_balance!=null){if(S.profile)S.profile.balance=row.new_balance;$('balanceValue').textContent=credits(row.new_balance)}notice('Ticket confirmed. Your virtual-credit balance has been updated.','ok');S.white=[];S.bonus=null;syncPicker();await loadMyTickets()}

function renderEvent(){const e=S.event,st=statusFor(e);document.title=`${e.title} — DRAW//01`;$('status').textContent=st;$('title').textContent=e.title;$('description').textContent=e.description||'Build tickets for this event and follow the draw result here.';$('prize').textContent=credits(e.prize_amount);$('prizeMode').textContent=e.prize_mode==='split_pool'?'Prize pool is split across winning tickets.':'Fixed prize per winning ticket.';$('ticketPrice').textContent=credits(e.ticket_price);$('ticketLimit').textContent=`${e.max_tickets_per_user} tickets`;$('cutoff').textContent=fmt(e.cutoff_at);$('drawTime').textContent=fmt(e.draw_at);$('buyCost').textContent=credits(e.ticket_price);$('rulesText').textContent=`Choose ${e.white_ball_count} unique numbers from 1–${e.white_ball_max}${e.bonus_ball_enabled?` plus 1 bonus ball from 1–${e.bonus_ball_max}`:''}. Each confirmed ticket uses ${credits(e.ticket_price)}.`;buildPicker();renderResult()}
function renderResult(){const e=S.event,root=$('resultNumbers');root.replaceChildren();if(e.status!=='completed'||!e.winning_numbers?.length){$('resultTitle').textContent=statusFor(e)==='AWAITING DRAW'?'Awaiting admin draw':'Waiting for draw';$('resultMeta').textContent='Winning numbers will appear here after the event is completed.';return}$('resultTitle').textContent='Completed result';e.winning_numbers.forEach(n=>{const s=document.createElement('span');s.textContent=String(n).padStart(2,'0');root.appendChild(s)});if(e.winning_bonus_ball){const s=document.createElement('span');s.className='bonus';s.textContent=String(e.winning_bonus_ball).padStart(2,'0');root.appendChild(s)}$('resultMeta').textContent=`${e.winning_ticket_count} winning ticket${e.winning_ticket_count===1?'':'s'} · ${credits(e.prize_per_winning_ticket)} awarded per winning ticket.`}

async function load(){if(!supabase||!slug){$('loading').textContent='Event link is invalid.';return}const {data,error}=await supabase.from('lottery_events').select('*').eq('slug',slug).maybeSingle();if(error||!data){$('loading').textContent='This event is unavailable or not public.';return}S.event=data;const {data:s}=await supabase.auth.getSession();S.session=s.session;await loadProfile();renderEvent();await loadMyTickets();$('loading').hidden=true;$('eventApp').hidden=false}

$('loginBtn').onclick=login;$('logoutBtn').onclick=logout;$('quickPick').onclick=quickPick;$('buyBtn').onclick=buy;
if(supabase)supabase.auth.onAuthStateChange(async(_e,session)=>{S.session=session;await loadProfile();if(S.event)await loadMyTickets()});
load();
