import { createClient } from 'https://cdn.jsdelivr.net/npm/@supabase/supabase-js@2.117.2/+esm';
import { SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, APP_URL, BACKEND_READY } from './config.js';
import { EventDrawMachine } from './draw-machine.js?v=2';

const supabase = BACKEND_READY ? createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, { auth: { persistSession: true, detectSessionInUrl: true, autoRefreshToken: true } }) : null;
const $ = id => document.getElementById(id);
const slug = new URLSearchParams(location.search).get('e');
const DRAW_SEGMENT_MS = 60000;
const DRAW_START_DELAY_MS = 1500;
const S = {
  event:null, session:null, profile:null, white:[], bonus:null, tickets:[], tiers:[], machine:null, channel:null, refreshTimer:null, pickerKey:'',
  publicWinners:[], publicWinnersEventId:null, revealedRanks:new Set(), revealActive:false, revealComplete:false, revealTotal:0
};

function credits(v){return `${Number(v||0).toLocaleString()} credits`}
function fmt(v){return v?new Date(v).toLocaleString([], {month:'short',day:'numeric',hour:'numeric',minute:'2-digit'}):'—'}
function esc(v){return String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function revealEnd(e){if(!e?.completed_at)return 0;return new Date(e.completed_at).getTime()+DRAW_START_DELAY_MS+Math.max(1,Number(e.winner_count||1))*DRAW_SEGMENT_MS}
function revealWindowOpen(e){return e?.status==='completed'&&Date.now()<revealEnd(e)}
function statusFor(e){if(e.status==='completed')return revealWindowOpen(e)||S.revealActive?'LIVE DRAW':'COMPLETED';if(e.status==='cancelled')return'CANCELLED';const n=Date.now();if(e.opens_at&&n<new Date(e.opens_at).getTime())return'UPCOMING';if(e.schedule_mode==='manual')return'OPEN';if(e.cutoff_at&&n<new Date(e.cutoff_at).getTime())return'OPEN';if(e.draw_at&&n<new Date(e.draw_at).getTime())return'LOCKED';return'AWAITING DRAW'}
function notice(m,type=''){$('notice').textContent=m;$('notice').className=`notice${type?' '+type:''}`}
function randomInt(max){const lim=Math.floor(0x100000000/max)*max,b=new Uint32Array(1);do crypto.getRandomValues(b);while(b[0]>=lim);return b[0]%max}
function uniqueRandom(count,max){const s=new Set();while(s.size<count)s.add(randomInt(max)+1);return [...s].sort((a,b)=>a-b)}
function capacityText(e){const p=e.max_players==null?'unlimited players':`${Number(e.max_players).toLocaleString()} players`;const t=e.max_total_tickets==null?'unlimited total tickets':`${Number(e.max_total_tickets).toLocaleString()} total tickets`;return `${p} · ${t}`}
function pickerConfigKey(e){return [e.id,e.white_ball_count,e.white_ball_max,e.bonus_ball_enabled,e.bonus_ball_max].join(':')}

async function login(){if(!supabase)return;localStorage.setItem('draw01_post_login_event',slug||'');const {error}=await supabase.auth.signInWithOAuth({provider:'google',options:{redirectTo:APP_URL}});if(error)notice(error.message,'error')}
async function logout(){if(!supabase)return;await supabase.auth.signOut();S.session=null;S.profile=null;window.Draw01Shell?.setSession(null);renderAuth();await loadMyTickets()}

function renderAuth(){const user=S.session?.user;if($('loginBtn'))$('loginBtn').hidden=!!user;if($('accountCard'))$('accountCard').hidden=!user;if(!user){window.Draw01Shell?.setSession(null);return}window.Draw01Shell?.setSession(S.session);const m=user.user_metadata||{},name=S.profile?.display_name||m.full_name||m.name||user.email?.split('@')[0]||'Player';if($('userName'))$('userName').textContent=name;if($('userAvatar'))$('userAvatar').src=S.profile?.avatar_url||m.avatar_url||`https://ui-avatars.com/api/?name=${encodeURIComponent(name)}`;window.Draw01Shell?.setBalance(S.profile?.balance||0)}

function buildPicker(){const e=S.event,w=$('whiteGrid'),b=$('bonusGrid');w.replaceChildren();b.replaceChildren();for(let n=1;n<=e.white_ball_max;n++){const x=document.createElement('button');x.type='button';x.className='num';x.textContent=n;x.dataset.n=n;x.onclick=()=>toggleWhite(n);w.appendChild(x)}if(e.bonus_ball_enabled){$('bonusBlock').hidden=false;for(let n=1;n<=e.bonus_ball_max;n++){const x=document.createElement('button');x.type='button';x.className='num';x.textContent=n;x.dataset.n=n;x.onclick=()=>toggleBonus(n);b.appendChild(x)}}else $('bonusBlock').hidden=true;S.pickerKey=pickerConfigKey(e);syncPicker()}
function toggleWhite(n){const i=S.white.indexOf(n);if(i>=0)S.white.splice(i,1);else if(S.white.length<S.event.white_ball_count)S.white.push(n);S.white.sort((a,b)=>a-b);syncPicker()}
function toggleBonus(n){S.bonus=S.bonus===n?null:n;syncPicker()}
function syncPicker(){const e=S.event;if(!e||!$('whiteGrid'))return;[...$('whiteGrid').children].forEach(x=>{const n=Number(x.dataset.n),sel=S.white.includes(n);x.classList.toggle('selected',sel);x.classList.toggle('locked',S.white.length>=e.white_ball_count&&!sel)});[...$('bonusGrid').children].forEach(x=>x.classList.toggle('selected',S.bonus===Number(x.dataset.n)));$('whiteCount').textContent=`${S.white.length} / ${e.white_ball_count}`;$('bonusCount').textContent=`${S.bonus?1:0} / 1`;renderPreview();const ready=S.white.length===e.white_ball_count&&(!e.bonus_ball_enabled||S.bonus);const open=statusFor(e)==='OPEN';$('buyBtn').disabled=!ready||!open;$('buyHint').textContent=!open?'Ticket sales are not currently open.':ready?(S.session?'Ready to confirm with your balance.':'Login will be requested when you confirm.'):'Choose all required numbers.'}
function renderPreview(){const e=S.event,root=$('ticketPreview');root.replaceChildren();for(let i=0;i<e.white_ball_count;i++){const x=document.createElement('span');x.className='preview-ball'+(S.white[i]?'':' empty');x.textContent=S.white[i]?String(S.white[i]).padStart(2,'0'):'—';root.appendChild(x)}if(e.bonus_ball_enabled){const p=document.createElement('span');p.className='preview-ball bonus'+(S.bonus?'':' empty');p.textContent=S.bonus?String(S.bonus).padStart(2,'0'):'B';root.appendChild(p)}}
function quickPick(){S.white=uniqueRandom(S.event.white_ball_count,S.event.white_ball_max);S.bonus=S.event.bonus_ball_enabled?randomInt(S.event.bonus_ball_max)+1:null;syncPicker()}

async function loadProfile(){if(!S.session?.user){S.profile=null;renderAuth();return}const {data,error}=await supabase.from('profiles').select('id,display_name,avatar_url,balance,role').eq('id',S.session.user.id).maybeSingle();if(!error)S.profile=data;renderAuth()}
function ticketWinnerVisible(t){if(!t?.is_winner)return false;if(S.event?.status!=='completed')return !!t.is_winner;if(S.revealComplete||!revealWindowOpen(S.event))return true;return S.revealedRanks.has(Number(t.winner_rank))}
async function loadMyTickets(){const root=$('myTickets');if(!S.session?.user){S.tickets=[];root.innerHTML='<p class="muted">Sign in to see your entries.</p>';$('ticketUsage').textContent=`0 / ${S.event?.max_tickets_per_user||0}`;return}const {data,error}=await supabase.from('event_tickets').select('id,white_numbers,bonus_ball,price_paid,is_winner,winner_rank,prize_awarded,created_at').eq('event_id',S.event.id).eq('user_id',S.session.user.id).order('created_at',{ascending:false});if(error){root.innerHTML=`<p class="muted">${esc(error.message)}</p>`;return}S.tickets=data||[];$('ticketUsage').textContent=`${S.tickets.length} / ${S.event.max_tickets_per_user}`;root.replaceChildren();if(!S.tickets.length){root.innerHTML='<p class="muted">No entries for this event yet.</p>';return}S.tickets.forEach((t,i)=>{const el=document.createElement('div');el.className='entry';const showWinner=ticketWinnerVisible(t);const winner=showWinner?` · <span class="winner">#${t.winner_rank} WINNER</span>`:'';el.innerHTML=`<strong>Ticket ${S.tickets.length-i}${winner}</strong><small>${t.white_numbers.map(n=>String(n).padStart(2,'0')).join('  ')}${t.bonus_ball?` + ${String(t.bonus_ball).padStart(2,'0')}`:''} · ${credits(t.price_paid)}${showWinner&&Number(t.prize_awarded)>0?` · Prize ${credits(t.prize_awarded)}`:''}</small>`;root.appendChild(el)})}

async function buy(){if(!S.session?.user){await login();return}if(S.tickets.length>=S.event.max_tickets_per_user){notice('You have reached this event’s ticket limit.','error');return}const btn=$('buyBtn');btn.disabled=true;btn.textContent='Confirming…';const {data,error}=await supabase.rpc('purchase_event_ticket',{p_event_id:S.event.id,p_white_numbers:S.white,p_bonus_ball:S.event.bonus_ball_enabled?S.bonus:null});btn.textContent='Confirm ticket';if(error){notice(error.message,'error');syncPicker();return}const row=Array.isArray(data)?data[0]:data;if(row?.new_balance!=null){if(S.profile)S.profile.balance=row.new_balance;window.Draw01Shell?.setBalance(row.new_balance)}notice('Ticket confirmed. Your virtual-credit balance has been updated.','ok');S.white=[];S.bonus=null;syncPicker();await Promise.all([loadMyTickets(),loadProfile()])}

function prizeText(){if(!S.tiers.length)return`${S.event.winner_count||1} ranked winner${(S.event.winner_count||1)===1?'':'s'}`;return S.tiers.map(t=>`#${t.rank} ${credits(t.prize_amount)}`).join(' · ')}
function applyHeroCover(e){const hero=document.querySelector('.event-hero');if(!hero)return;let layer=hero.querySelector('.event-hero-cover');if(!e.cover_image_url){hero.classList.remove('has-cover');if(layer)layer.remove();return}if(!layer){layer=document.createElement('div');layer.className='event-hero-cover';layer.innerHTML='<img alt=""><div></div>';hero.prepend(layer)}const img=layer.querySelector('img');img.src=e.cover_image_url;img.alt=`${e.title} cover`;hero.classList.add('has-cover')}
function updateEventMeta(){const e=S.event,st=statusFor(e);document.title=`${e.title} — GAME ZONE`;applyHeroCover(e);$('status').textContent=st;$('title').textContent=e.title;$('description').textContent=e.description||'Build tickets for this event and follow the draw result here.';$('prize').textContent=credits(e.prize_amount);$('prizeMode').textContent=prizeText();$('ticketPrice').textContent=credits(e.ticket_price);$('ticketLimit').textContent=`${e.max_tickets_per_user} tickets`;if(e.schedule_mode==='manual'){$('cutoff').textContent='Open until admin closes';$('drawTime').textContent='Admin-triggered'}else{$('cutoff').textContent=fmt(e.cutoff_at);$('drawTime').textContent=fmt(e.draw_at)}$('buyCost').textContent=credits(e.ticket_price);$('rulesText').textContent=`Choose ${e.white_ball_count} unique numbers from 1–${e.white_ball_max}${e.bonus_ball_enabled?` plus 1 bonus ball from 1–${e.bonus_ball_max}`:''}. Each confirmed ticket uses ${credits(e.ticket_price)}. Event capacity: ${capacityText(e)}. Winners are selected only from tickets submitted to this event.`}
function renderEvent({full=false,initial=false}={}){const e=S.event;updateEventMeta();if(full||S.pickerKey!==pickerConfigKey(e))buildPicker();else syncPicker();S.machine?.setEvent(e,{initial});renderResult()}
function winnerBalls(w){return `<div class="winner-ticket-balls">${(w.white_numbers||[]).map(n=>`<span>${String(n).padStart(2,'0')}</span>`).join('')}${w.bonus_ball!=null?`<span class="bonus">${String(w.bonus_ball).padStart(2,'0')}</span>`:''}</div>`}
function normalizeWinnerRow(w,i=0){return{rank:Number(w.winner_rank??w.rank??i+1),prize:Number(w.prize_awarded??w.prize??0),white_numbers:Array.isArray(w.white_numbers)?w.white_numbers:[],bonus_ball:w.bonus_ball??null,display_name:w.display_name||'',avatar_url:w.avatar_url||'',ticket_id:w.ticket_id||'',user_id:w.user_id||''}}
function winnerRows(){if(S.publicWinners.length)return S.publicWinners.map(normalizeWinnerRow).sort((a,b)=>a.rank-b.rank);const summary=Array.isArray(S.event?.winner_summary)?S.event.winner_summary:[];return summary.map(normalizeWinnerRow).sort((a,b)=>a.rank-b.rank)}
function winnerIdentity(w){const name=w.display_name||`Winner #${w.rank}`;const avatar=w.avatar_url?`<img src="${esc(w.avatar_url)}" alt="${esc(name)}">`:`<span class="ranked-winner-avatar">${esc((name||'W')[0])}</span>`;return `<div class="ranked-winner-identity">${avatar}<div><b>${esc(name)}</b><small>${w.ticket_id?`Ticket ${esc(String(w.ticket_id).slice(0,8))}`:'Winning ticket'}</small></div></div>`}
function renderResult(){
  const e=S.event,root=$('resultNumbers');root.replaceChildren();
  if(e.status!=='completed'){$('resultTitle').textContent=statusFor(e)==='AWAITING DRAW'?'Draw in progress':'Waiting for draw';$('resultMeta').textContent=e.schedule_mode==='manual'?'The admin will draw from the existing ticket pool when the event is ready.':'The ranked live machine will reveal every winner one by one after the scheduled server draw.';return}
  const winners=winnerRows();const live=S.revealActive||revealWindowOpen(e);const visible=S.revealComplete||!live?winners:winners.filter(w=>S.revealedRanks.has(w.rank));const total=S.revealTotal||Number(e.winner_count||winners.length||1);
  $('resultTitle').textContent=live&&!S.revealComplete?'Live winner board':'Final winner board';
  if(!visible.length){root.innerHTML='<div class="draw-result-locked"><strong>Results are locked behind the live reveal</strong><span>No winner number will appear here before that position is declared by the draw machine.</span><div class="result-live-progress"><i></i>Live sequence in progress</div></div>';$('resultMeta').textContent=`0 of ${total} winner positions revealed. The lowest configured position comes first; #1 comes last.`;return}
  const wrap=document.createElement('div');wrap.className='ranked-winners';visible.sort((a,b)=>a.rank-b.rank).forEach(w=>{const row=document.createElement('div');row.className='ranked-winner-row'+(w.rank===1?' rank-one':'');row.innerHTML=`<div class="ranked-winner-head"><strong>#${w.rank} winner</strong><span>${credits(w.prize)}</span></div>${winnerIdentity(w)}${winnerBalls(w)}`;wrap.appendChild(row)});root.appendChild(wrap);
  if(live&&!S.revealComplete){$('resultMeta').innerHTML=`${visible.length} of ${total} positions revealed. Unrevealed winners stay hidden until their animation finishes. <span class="result-live-progress"><i></i>Live</span>`}else{$('resultMeta').textContent=`${winners.length} ranked winner ticket${winners.length===1?'':'s'} — full reveal complete.`}
}

async function loadTiers(){if(!S.event)return;const {data}=await supabase.from('event_prize_tiers').select('rank,prize_amount').eq('event_id',S.event.id).order('rank');S.tiers=data||[]}
async function loadPublicWinners(force=false){if(!supabase||!S.event||S.event.status!=='completed')return;if(!force&&S.publicWinnersEventId===S.event.id&&S.publicWinners.length)return;const {data,error}=await supabase.rpc('get_public_event_winners',{p_event_id:S.event.id});if(!error&&Array.isArray(data)){S.publicWinners=data;S.publicWinnersEventId=S.event.id}}
function bindDrawMachine(){const mount=$('drawMachineMount');if(!mount)return;mount.addEventListener('gmdraw:reset',e=>{const d=e.detail||{};S.revealedRanks=new Set();S.revealTotal=(d.winners||[]).length||Number(S.event?.winner_count||0);S.revealComplete=false;S.revealActive=!d.historical;if(S.revealActive)document.documentElement.dataset.drawRevealActive='1';else delete document.documentElement.dataset.drawRevealActive;renderResult();loadMyTickets()});mount.addEventListener('gmdraw:rankstart',()=>{S.revealActive=true;document.documentElement.dataset.drawRevealActive='1';updateEventMeta();renderResult()});mount.addEventListener('gmdraw:rankreveal',e=>{const rank=Number(e.detail?.winner?.rank);if(Number.isFinite(rank))S.revealedRanks.add(rank);renderResult();loadMyTickets()});mount.addEventListener('gmdraw:complete',e=>{(e.detail?.winners||[]).forEach(w=>S.revealedRanks.add(Number(w.rank)));S.revealActive=false;S.revealComplete=true;delete document.documentElement.dataset.drawRevealActive;updateEventMeta();renderResult();loadMyTickets();loadProfile()})}

async function refreshEvent(){if(!S.event||document.hidden)return scheduleRefresh();const {data,error}=await supabase.from('lottery_events').select('*').eq('id',S.event.id).maybeSingle();if(!error&&data){const becameCompleted=S.event.status!=='completed'&&data.status==='completed';S.event=data;if(becameCompleted||data.status==='completed')await loadPublicWinners(becameCompleted);renderEvent({full:false});await loadMyTickets()}scheduleRefresh()}
function refreshDelay(){if(!S.event)return 30000;if(S.event.status==='completed'&&revealWindowOpen(S.event))return 3000;if(S.event.status==='completed'||S.event.status==='cancelled')return 30000;if(S.event.schedule_mode==='manual')return 15000;const drawAt=S.event.draw_at?new Date(S.event.draw_at).getTime():0;const delta=drawAt-Date.now();if(delta<=0)return 2200;if(delta<120000)return 3000;if(delta<600000)return 10000;return 30000}
function scheduleRefresh(){clearTimeout(S.refreshTimer);S.refreshTimer=setTimeout(refreshEvent,refreshDelay())}
function setupRealtime(){if(!supabase||!S.event)return;try{if(S.channel)supabase.removeChannel(S.channel);S.channel=supabase.channel(`event-live-${S.event.id}`).on('postgres_changes',{event:'UPDATE',schema:'public',table:'lottery_events',filter:`id=eq.${S.event.id}`},async payload=>{if(!payload?.new)return;const becameCompleted=S.event?.status!=='completed'&&payload.new.status==='completed';S.event=payload.new;if(becameCompleted||S.event.status==='completed')await loadPublicWinners(becameCompleted);renderEvent({full:false});await loadMyTickets();scheduleRefresh()}).subscribe()}catch(_e){/* polling remains the fallback */}}

async function load(){if(!supabase||!slug){$('loading').textContent='Event link is invalid.';return}const {data,error}=await supabase.from('lottery_events').select('*').eq('slug',slug).maybeSingle();if(error||!data){$('loading').textContent='This event is unavailable or not public.';return}S.event=data;await loadTiers();if(S.event.status==='completed')await loadPublicWinners(true);const {data:s}=await supabase.auth.getSession();S.session=s.session;window.Draw01Shell?.setSession(S.session);await loadProfile();$('loading').hidden=true;$('eventApp').hidden=false;S.machine=new EventDrawMachine($('drawMachineMount'));bindDrawMachine();renderEvent({full:true,initial:true});await loadMyTickets();setupRealtime();scheduleRefresh()}

if($('loginBtn'))$('loginBtn').onclick=login;if($('logoutBtn'))$('logoutBtn').onclick=logout;$('quickPick').onclick=quickPick;$('buyBtn').onclick=buy;
if(supabase)supabase.auth.onAuthStateChange(async(_e,session)=>{S.session=session;window.Draw01Shell?.setSession(session);await loadProfile();if(S.event)await loadMyTickets()});
window.addEventListener('beforeunload',()=>{clearTimeout(S.refreshTimer);S.machine?.destroy();if(S.channel&&supabase)supabase.removeChannel(S.channel)});
document.addEventListener('visibilitychange',()=>{if(!document.hidden){clearTimeout(S.refreshTimer);refreshEvent()}});
load();
