(function(){
'use strict';
var BASE='https://mwtlsnneooxmryondrex.supabase.co';
var KEY='sb_publishable_zfXYDH1qSZURp8bRHgnBrQ_7t7-3BMd';
function $(id){return document.getElementById(id)}
function pct(v){return (Number(v||0)*100).toFixed(2)+'%'}
function game(slug){return fetch(BASE+'/rest/v1/games?select=slug,title,description,status,min_bet,max_bet,bet_steps,rtp,house_edge,version,config&slug=eq.'+encodeURIComponent(slug)+'&limit=1',{headers:{apikey:KEY}}).then(function(r){if(!r.ok)throw new Error('Game catalog unavailable');return r.json()}).then(function(rows){return rows&&rows[0]||null})}
Promise.all([game('classic-slot'),game('neon-plinko')]).then(function(list){var active=0,slot=list[0],plinko=list[1];if(slot){$('slotTitle').textContent=slot.title;$('slotDescription').textContent=slot.description;$('slotRtp').textContent=pct(slot.rtp);$('slotEdge').textContent=pct(slot.house_edge);$('slotBet').textContent=Number(slot.min_bet)+'–'+Number(slot.max_bet)+' CR';if(slot.status==='active')active++;else{$('slotPlayBtn').removeAttribute('href');$('slotPlayBtn').classList.add('disabled');$('slotPlayBtn').querySelector('span').textContent='Coming soon'}}if(plinko){$('plinkoTitle').textContent=plinko.title;$('plinkoDescription').textContent=plinko.description;var med=plinko.config&&plinko.config.riskModes&&plinko.config.riskModes.medium;$('plinkoRtp').textContent=pct(med&&med.rtp||plinko.rtp);$('plinkoBet').textContent=Number(plinko.min_bet)+'–'+Number(plinko.max_bet)+' CR';if(plinko.status==='active')active++;else{$('plinkoPlayBtn').removeAttribute('href');$('plinkoPlayBtn').classList.add('disabled');$('plinkoPlayBtn').querySelector('span').textContent='Coming soon'}}$('activeGames').textContent=String(active)}).catch(function(){/* Static cards remain usable as fallback. */});
})();
