import { createClient } from 'https://cdn.jsdelivr.net/npm/@supabase/supabase-js@2.117.2/+esm';
import { SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, APP_URL, BACKEND_READY } from './config.js';

const supabase = BACKEND_READY ? createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {auth:{persistSession:true,detectSessionInUrl:true,autoRefreshToken:true}}) : null;
const $=id=>document.getElementById(id);
let session=null,events=[];
function esc(v){return String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function credits(v){return `${Number(v||0).toLocaleString()} credits`}
function fmt(v){return new Date(v).toLocaleString([], {month:'short',day:'numeric',hour:'numeric',minute:'2-digit'})}
function statusFor(e){if(e.status==='completed')return'COMPLETED';if(e.status==='cancelled')return'CANCELLED';const n=Date.now();if(n<new Date(e.opens_at).getTime())return'UPCOMING';if(n<new Date(e.cutoff_at).getTime())return'OPEN';if(n<new Date(e.draw_at).getTime())return'LOCKED';return'AWAITING DRAW'}
async function login(){if(!supabase)return;const {error}=await supabase.auth.signInWithOAuth({provider:'google',options:{redirectTo:APP_URL}});if(error)console.error(error)}
async function logout(){if(!supabase)return;await supabase.auth.signOut()}
async function renderAuth(){const user=session?.user;$('loginBtn').hidden=!!user;$('accountCard').hidden=!user;$('walletStrip').hidden=!user;if(!user){$('walletBalance').textContent='0 credits';return}const m=user.user_metadata||{};$('userName').textContent=m.full_name||m.name||user.email?.split('@')[0]||'Player';$('userEmail').textContent=user.email||'';$('userAvatar').src=m.avatar_url||`https://ui-avatars.com/api/?name=${encodeURIComponent($('userName').textContent)}`;const {data}=await supabase.from('profiles').select('balance').eq('id',user.id).maybeSingle();$('walletBalance').textContent=credits(data?.balance||0)}
function card(e){const st=statusFor(e),a=document.createElement('a');a.className='event-card';a.href=`event.html?e=${encodeURIComponent(e.slug)}`;a.innerHTML=`<div class="event-card-top"><span class="event-status ${st.toLowerCase().replace(/\s/g,'-')}">${st}</span><span class="event-arrow">↗</span></div><h3>${esc(e.title)}</h3><p>${esc(e.description||'Open this event to view its rules and choose your numbers.')}</p><div class="event-metrics"><div><span>Prize</span><strong>${credits(e.prize_amount)}</strong></div><div><span>Ticket</span><strong>${credits(e.ticket_price)}</strong></div><div><span>Limit</span><strong>${e.max_tickets_per_user} / player</strong></div><div><span>Draw</span><strong>${fmt(e.draw_at)}</strong></div></div>`;return a}
function renderEvents(){const grid=$('lotteryEventsGrid');grid.replaceChildren();const visible=events.filter(e=>e.status!=='draft');if(!visible.length){grid.innerHTML='<div class="events-empty">No public events yet. New events created by admin will appear here automatically.</div>';return}visible.forEach(e=>grid.appendChild(card(e)));const statuses=visible.map(statusFor);$('openCount').textContent=statuses.filter(s=>s==='OPEN').length;$('upcomingCount').textContent=statuses.filter(s=>s==='UPCOMING'||s==='LOCKED'||s==='AWAITING DRAW').length;$('completedCount').textContent=statuses.filter(s=>s==='COMPLETED').length}
async function loadEvents(){if(!supabase)return;const {data,error}=await supabase.from('lottery_events').select('id,slug,title,description,status,ticket_price,prize_amount,max_tickets_per_user,opens_at,cutoff_at,draw_at').order('draw_at',{ascending:true}).limit(100);if(error){$('lotteryEventsGrid').innerHTML='<div class="events-empty">Could not load events right now.</div>';return}events=data||[];renderEvents()}
async function handlePending(){if(!supabase)return;const pending=localStorage.getItem('draw01_post_login_event');if(!pending)return;const {data}=await supabase.auth.getSession();if(data.session){localStorage.removeItem('draw01_post_login_event');location.replace(`event.html?e=${encodeURIComponent(pending)}`)}}
async function init(){if(!supabase)return;const {data}=await supabase.auth.getSession();session=data.session;await renderAuth();await loadEvents();await handlePending();supabase.auth.onAuthStateChange(async(_event,s)=>{session=s;await renderAuth()});setInterval(renderEvents,30000)}
$('loginBtn').onclick=login;$('logoutBtn').onclick=logout;init();