(function(){
'use strict';
var BASE='https://mwtlsnneooxmryondrex.supabase.co',KEY='sb_publishable_zfXYDH1qSZURp8bRHgnBrQ_7t7-3BMd',REF='mwtlsnneooxmryondrex';
var S={session:null,user:null,profile:null,events:[],tickets:[],profiles:[],ledger:[],audit:[],editing:null,balanceUser:null,timer:null};
function $(id){return document.getElementById(id)}
function esc(v){return String(v==null?'':v).replace(/[&<>"']/g,function(c){return {'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]})}
function credits(v){return Number(v||0).toLocaleString(undefined,{maximumFractionDigits:2})+' cr'}
function fmt(v){return v?new Date(v).toLocaleString([], {month:'short',day:'numeric',hour:'numeric',minute:'2-digit'}):'—'}
function localInput(v){if(!v)return'';var d=new Date(v);return new Date(d.getTime()-d.getTimezoneOffset()*60000).toISOString().slice(0,16)}
function slugify(v){return String(v||'').toLowerCase().trim().replace(/[^a-z0-9]+/g,'-').replace(/^-+|-+$/g,'')}
function session(){try{var x=JSON.parse(localStorage.getItem('sb-'+REF+'-auth-token')||'null');if(x&&x.access_token)return x;if(x&&x.currentSession&&x.currentSession.access_token)return x.currentSession;if(x&&x.session&&x.session.access_token)return x.session;return null}catch(e){return null}}
function req(path,opt){opt=opt||{};var h=Object.assign({},opt.headers||{});h.apikey=KEY;if(S.session)h.Authorization='Bearer '+S.session.access_token;if(opt.body)h['Content-Type']='application/json';return fetch(BASE+path,Object.assign({},opt,{headers:h})).then(function(r){return r.text().then(function(t){var d;try{d=t?JSON.parse(t):null}catch(e){d=t}if(!r.ok)throw new Error((d&&d.message)||(d&&d.error_description)||(d&&d.error)||('HTTP '+r.status));return d})})}
function rest(path,opt){return req('/rest/v1/'+path,opt)}
function rpc(name,args){return rest('rpc/'+name,{method:'POST',body:JSON.stringify(args||{})})}
function safe(p,fallback){return p.catch(function(e){console.warn(e);return fallback})}
function note(m,e){var t=$('toast');t.textContent=m;t.className=e?'err':'';t.style.display='block';clearTimeout(t._h);t._h=setTimeout(function(){t.style.display='none'},4200)}
function statusView(e){if(!e)return'none';if(e.status==='draft'||e.status==='completed'||e.status==='cancelled')return e.status;var n=Date.now();if(n<new Date(e.opens_at).getTime())return'upcoming';if(n<new Date(e.cutoff_at).getTime())return'open';if(n<new Date(e.draw_at).getTime())return'locked';return'awaiting'}
function statusLabel(e){var s=statusView(e);return s==='awaiting'?'AWAITING DRAW':s.toUpperCase()}
function pmap(){var m={};S.profiles.forEach(function(p){m[p.id]=p});return m}
function emap(){var m={};S.events.forEach(function(e){m[e.id]=e});return m}
function ticketCount(id){return S.tickets.filter(function(t){return t.event_id===id}).length}
function nextEvent(){return S.events.filter(function(e){return e.status==='published'}).sort(function(a,b){var sa=statusView(a)==='open'?0:statusView(a)==='locked'?1:statusView(a)==='upcoming'?2:3,sb=statusView(b)==='open'?0:statusView(b)==='locked'?1:statusView(b)==='upcoming'?2:3;return sa-sb||new Date(a.draw_at)-new Date(b.draw_at)})[0]||null}
function button(label,cls,fn){var b=document.createElement('button');b.type='button';b.className='btn '+(cls||'ghost')+' compact';b.textContent=label;b.onclick=fn;return b}
function info(k,v){return '<div class="info-card"><span>'+esc(k)+'</span><strong>'+esc(v)+'</strong></div>'}
function numbersHtml(t){var h='<div class="number-chips">';(t.white_numbers||[]).forEach(function(n){h+='<span>'+String(n).padStart(2,'0')+'</span>'});if(t.bonus_ball!=null)h+='<span class="bonus">'+String(t.bonus_ball).padStart(2,'0')+'</span>';return h+'</div>'}

function boot(){S.session=session();if(!S.session){$('gateMsg').textContent='No active Google session. Sign in on the public site, then return here.';return}req('/auth/v1/user').then(function(u){S.user=u;return rest('profiles?select=id,display_name,email,role,balance&id=eq.'+encodeURIComponent(u.id)+'&limit=1')}).then(function(rows){var p=rows&&rows[0];if(!p)throw new Error('Profile not found');if(p.role!=='admin')throw new Error('This account is not an admin');S.profile=p;$('adminName').textContent=p.display_name||'Admin';$('adminEmail').textContent=p.email||'';$('gate').style.display='none';$('app').hidden=false;return load()}).catch(function(e){$('gateMsg').textContent='Admin check failed: '+e.message;note(e.message,true)})}

function load(){return Promise.all([
  safe(rest('lottery_events?select=*&order=created_at.desc&limit=500'),[]),
  safe(rest('event_tickets?select=id,event_id,user_id,white_numbers,bonus_ball,price_paid,is_winner,prize_awarded,created_at&order=created_at.desc&limit=5000'),[]),
  safe(rest('profiles?select=id,display_name,email,role,balance,created_at&order=created_at.desc&limit=1000'),[]),
  safe(rest('balance_ledger?select=*&order=created_at.desc&limit=2000'),[]),
  safe(rest('audit_logs?select=*&order=created_at.desc&limit=500'),[])
]).then(function(x){S.events=x[0]||[];S.tickets=x[1]||[];S.profiles=x[2]||[];S.ledger=x[3]||[];S.audit=x[4]||[];render()}).catch(function(e){note('Dashboard load failed: '+e.message,true)})}

function render(){renderStats();renderOverview();renderEvents();renderTickets();renderPlayers();renderLedger();renderAudit();startCountdown()}
function renderStats(){var open=S.events.filter(function(e){return statusView(e)==='open'}).length,totalCredits=S.profiles.reduce(function(a,p){return a+Number(p.balance||0)},0),n=nextEvent();$('statEvents').textContent=S.events.length;$('statOpen').textContent=open;$('statTickets').textContent=S.tickets.length;$('statPlayers').textContent=S.profiles.length;$('statCredits').textContent=Number(totalCredits).toLocaleString(undefined,{maximumFractionDigits:0});$('statNext').textContent=n?'…':'—';$('statNextMeta').textContent=n?fmt(n.draw_at):'Not scheduled'}
function startCountdown(){clearInterval(S.timer);function tick(){var e=nextEvent();if(!e){$('statNext').textContent='—';$('statNextMeta').textContent='Not scheduled';return}var target=new Date(e.draw_at).getTime(),sec=Math.max(0,Math.floor((target-Date.now())/1000)),d=Math.floor(sec/86400);sec%=86400;var h=Math.floor(sec/3600);sec%=3600;var m=Math.floor(sec/60),s=sec%60;$('statNext').textContent=d?d+'d '+String(h).padStart(2,'0')+'h':h?String(h).padStart(2,'0')+':'+String(m).padStart(2,'0')+':'+String(s).padStart(2,'0'):String(m).padStart(2,'0')+':'+String(s).padStart(2,'0');$('statNextMeta').textContent=e.title+' · '+fmt(e.draw_at)}tick();S.timer=setInterval(tick,1000)}
function renderOverview(){var e=nextEvent(),root=$('focusInfo'),actions=$('focusActions'),st=$('focusStatus');actions.innerHTML='';if(!e){$('focusTitle').textContent='No published event';st.textContent='—';st.className='status-pill';root.innerHTML='<div class="overview-empty">Create or publish an event to make it available to players.</div>';actions.appendChild(button('+ Create event','primary',openCreate));renderTimeline($('overviewAudit'),S.audit.slice(0,8));return}$('focusTitle').textContent=e.title;st.textContent=statusLabel(e);st.className='status-pill '+statusView(e);root.innerHTML=[info('Ticket price',credits(e.ticket_price)),info('Prize',credits(e.prize_amount)),info('Entries',String(ticketCount(e.id))),info('Per-player limit',String(e.max_tickets_per_user)),info('Cutoff',fmt(e.cutoff_at)),info('Draw',fmt(e.draw_at))].join('');appendEventActions(actions,e,true);renderTimeline($('overviewAudit'),S.audit.slice(0,8))}

function appendEventActions(root,e,compact){root.appendChild(button('View public page','ghost',function(){window.open('event.html?e='+encodeURIComponent(e.slug),'_blank')}));if(e.status!=='completed')root.appendChild(button('Edit','ghost',function(){openEdit(e)}));if(e.status==='draft')root.appendChild(button('Publish','primary',function(){changeStatus(e,'published')}));if(e.status==='published'&&Date.now()>=new Date(e.cutoff_at).getTime())root.appendChild(button('Run draw','primary',function(){runEvent(e)}));if(e.status==='published'||e.status==='draft')root.appendChild(button('Cancel','danger',function(){changeStatus(e,'cancelled')}));if((e.status==='draft'||e.status==='cancelled')&&ticketCount(e.id)===0)root.appendChild(button('Delete','danger',function(){deleteEvent(e)}))}
function renderEvents(){var f=$('eventStatusFilter').value||'all',rows=S.events.filter(function(e){return f==='all'||e.status===f}),root=$('eventList');$('eventSummary').textContent=rows.length+' events';root.innerHTML='';if(!rows.length){root.innerHTML='<div class="record-card"><div class="record-main"><strong>No events found</strong><div class="record-meta"><span>Create a new event or change the filter.</span></div></div></div>';return}rows.forEach(function(e){var row=document.createElement('div');row.className='record-card event-card-admin';var main=document.createElement('div');main.className='record-main';main.innerHTML='<div class="event-title-line"><strong>'+esc(e.title)+'</strong><span class="status-pill '+statusView(e)+'">'+esc(statusLabel(e))+'</span></div><div class="event-description">'+esc(e.description||'No description')+'</div><div class="record-meta"><span>Ticket <b>'+credits(e.ticket_price)+'</b></span><span>Prize <b>'+credits(e.prize_amount)+'</b></span><span>Limit <b>'+e.max_tickets_per_user+'</b></span><span>Entries <b>'+ticketCount(e.id)+'</b></span><span>Draw <b>'+esc(fmt(e.draw_at))+'</b></span></div>';if(e.status==='completed'&&e.winning_numbers)main.innerHTML+=numbersHtml({white_numbers:e.winning_numbers,bonus_ball:e.winning_bonus_ball});var actions=document.createElement('div');actions.className='record-actions';appendEventActions(actions,e,false);row.appendChild(main);row.appendChild(actions);root.appendChild(row)})}

function renderTickets(){var sel=$('ticketEventFilter'),prev=sel.value||'all';sel.innerHTML='<option value="all">All events</option>'+S.events.map(function(e){return '<option value="'+e.id+'">'+esc(e.title)+'</option>'}).join('');if(Array.prototype.some.call(sel.options,function(o){return o.value===prev}))sel.value=prev;var rows=S.tickets.filter(function(t){return sel.value==='all'||t.event_id===sel.value}),pm=pmap(),em=emap(),root=$('ticketList');$('ticketSummary').textContent=rows.length+' tickets';root.innerHTML='';if(!rows.length){root.innerHTML='<div class="record-card"><div class="record-main"><strong>No tickets found</strong></div></div>';return}rows.forEach(function(t){var p=pm[t.user_id]||{},e=em[t.event_id]||{},r=document.createElement('div');r.className='record-card';r.innerHTML='<div class="record-main"><div class="record-title"><strong>'+esc(p.display_name||p.email||'Player')+'</strong><span class="status-pill">'+esc(e.title||'Unknown event')+'</span></div>'+numbersHtml(t)+'<div class="record-meta"><span>Paid '+credits(t.price_paid)+'</span><span>'+esc(fmt(t.created_at))+'</span>'+(t.is_winner?'<span class="winner">WINNER · '+credits(t.prize_awarded)+'</span>':'<span class="muted">'+(e.status==='completed'?'Not a winner':'Pending result')+'</span>')+'</div></div>';root.appendChild(r)})}

function renderPlayers(){var root=$('playerList');root.innerHTML='';if(!S.profiles.length){root.innerHTML='<div class="record-card"><strong>No users yet</strong></div>';return}S.profiles.forEach(function(p){var row=document.createElement('div');row.className='record-card';var main=document.createElement('div');main.className='record-main';main.innerHTML='<div class="record-title"><strong>'+esc(p.display_name||'Player')+'</strong><span class="status-pill">'+esc((p.role||'player').toUpperCase())+'</span></div><div class="record-meta"><span>'+esc(p.email||'')+'</span><span class="credit-balance">'+credits(p.balance)+'</span><span>Joined '+esc(fmt(p.created_at))+'</span></div>';var a=document.createElement('div');a.className='record-actions';a.appendChild(button('Set balance','primary',function(){openBalance(p)}));var role=document.createElement('select');role.className='role-select';role.innerHTML='<option value="player">Player</option><option value="admin">Admin</option>';role.value=p.role;role.disabled=S.user&&p.id===S.user.id;role.onchange=function(){rpc('admin_set_user_role',{p_user_id:p.id,p_role:role.value}).then(function(){note('Role updated');return load()}).catch(function(e){note(e.message,true)})};a.appendChild(role);row.appendChild(main);row.appendChild(a);root.appendChild(row)})}

function renderLedger(){var sel=$('ledgerUserFilter'),prev=sel.value||'all';sel.innerHTML='<option value="all">All players</option>'+S.profiles.map(function(p){return '<option value="'+p.id+'">'+esc(p.display_name||p.email||'Player')+'</option>'}).join('');if(Array.prototype.some.call(sel.options,function(o){return o.value===prev}))sel.value=prev;var rows=S.ledger.filter(function(x){return sel.value==='all'||x.user_id===sel.value}),pm=pmap(),em=emap(),root=$('ledgerList');$('ledgerSummary').textContent=rows.length+' entries';root.innerHTML='';if(!rows.length){root.innerHTML='<div class="record-card"><strong>No balance movements yet</strong></div>';return}rows.forEach(function(x){var p=pm[x.user_id]||{},e=em[x.event_id]||{},r=document.createElement('div');r.className='record-card';var amount=Number(x.amount||0);r.innerHTML='<div class="record-main"><div class="record-title"><strong>'+esc(p.display_name||p.email||'Player')+'</strong><span class="status-pill">'+esc(String(x.entry_type||'entry').replace(/_/g,' ').toUpperCase())+'</span></div><div class="record-meta"><span class="ledger-amount '+(amount>=0?'plus':'minus')+'">'+(amount>=0?'+':'')+credits(amount)+'</span><span>Balance '+credits(x.balance_after)+'</span>'+(e.title?'<span>'+esc(e.title)+'</span>':'')+(x.note?'<span>'+esc(x.note)+'</span>':'')+'<span>'+esc(fmt(x.created_at))+'</span></div></div>';root.appendChild(r)})}

function renderTimeline(root,rows){var pm=pmap();root.innerHTML='';if(!rows.length){root.innerHTML='<div class="overview-empty">No activity yet.</div>';return}rows.forEach(function(a){var el=document.createElement('div');el.className='timeline-item';el.innerHTML='<i class="timeline-dot"></i><div><strong>'+esc(String(a.action||'activity').replace(/_/g,' '))+'</strong><small>'+esc((pm[a.actor_user_id]||{}).display_name||'System')+(a.entity_type?' · '+a.entity_type:'')+'</small></div><time>'+esc(fmt(a.created_at))+'</time>';root.appendChild(el)})}
function renderAudit(){renderTimeline($('auditList'),S.audit)}

function defaults(){var n=Date.now();return{open:new Date(n+5*60000),cut:new Date(n+65*60000),draw:new Date(n+70*60000)}}
function setLockedFields(locked){['fPrice','fWhiteCount','fWhiteMax','fBonusEnabled','fBonusMax'].forEach(function(id){$(id).disabled=!!locked});$('eventFormHint').textContent=locked?'Ticket price and number rules are locked because this event already has tickets. Prize, limits and schedule may still be edited.':'';$('eventFormHint').className='form-hint'+(locked?' warn':'')}
function openCreate(){S.editing=null;var d=defaults();$('eventModalKicker').textContent='CREATE EVENT';$('eventModalTitle').textContent='New public event';$('saveEventBtn').textContent='Create event';$('fTitle').value='';$('fSlug').value='';delete $('fSlug').dataset.touched;$('fDescription').value='';$('fPrice').value=10;$('fPrize').value=1000;$('fPrizeMode').value='split_pool';$('fLimit').value=5;$('fWhiteCount').value=5;$('fWhiteMax').value=69;$('fBonusEnabled').checked=true;$('fBonusMax').value=26;$('fOpen').value=localInput(d.open);$('fCutoff').value=localInput(d.cut);$('fDraw').value=localInput(d.draw);$('fStatus').value='draft';setLockedFields(false);syncBonusField();$('eventDialog').showModal()}
function openEdit(e){S.editing=e;$('eventModalKicker').textContent='EDIT EVENT';$('eventModalTitle').textContent=e.title;$('saveEventBtn').textContent='Save changes';$('fTitle').value=e.title||'';$('fSlug').value=e.slug||'';$('fSlug').dataset.touched='1';$('fDescription').value=e.description||'';$('fPrice').value=Number(e.ticket_price);$('fPrize').value=Number(e.prize_amount);$('fPrizeMode').value=e.prize_mode;$('fLimit').value=e.max_tickets_per_user;$('fWhiteCount').value=e.white_ball_count;$('fWhiteMax').value=e.white_ball_max;$('fBonusEnabled').checked=!!e.bonus_ball_enabled;$('fBonusMax').value=e.bonus_ball_max;$('fOpen').value=localInput(e.opens_at);$('fCutoff').value=localInput(e.cutoff_at);$('fDraw').value=localInput(e.draw_at);$('fStatus').value=e.status==='completed'?'published':e.status;setLockedFields(ticketCount(e.id)>0);syncBonusField();$('eventDialog').showModal()}
function syncBonusField(){if(!$('fBonusEnabled').disabled)$('fBonusMax').disabled=!$('fBonusEnabled').checked}
function formArgs(){var open=new Date($('fOpen').value),cut=new Date($('fCutoff').value),draw=new Date($('fDraw').value);if(!isFinite(open)||!isFinite(cut)||!isFinite(draw)||open>=cut||cut>=draw)throw new Error('Schedule must be: opens → cutoff → draw');return{p_title:$('fTitle').value.trim(),p_slug:$('fSlug').value.trim()||slugify($('fTitle').value),p_description:$('fDescription').value.trim(),p_ticket_price:Number($('fPrice').value),p_prize_amount:Number($('fPrize').value),p_prize_mode:$('fPrizeMode').value,p_max_tickets_per_user:Number($('fLimit').value),p_white_ball_count:Number($('fWhiteCount').value),p_white_ball_max:Number($('fWhiteMax').value),p_bonus_ball_enabled:$('fBonusEnabled').checked,p_bonus_ball_max:Number($('fBonusMax').value||1),p_opens_at:open.toISOString(),p_cutoff_at:cut.toISOString(),p_draw_at:draw.toISOString()}}
function saveEvent(ev){ev.preventDefault();var a;try{a=formArgs()}catch(e){note(e.message,true);return}var p;if(S.editing){a.p_event_id=S.editing.id;a.p_status=$('fStatus').value;p=rpc('admin_update_lottery_event',a)}else{a.p_publish=$('fStatus').value==='published';p=rpc('admin_create_lottery_event',a)}$('saveEventBtn').disabled=true;p.then(function(){$('eventDialog').close();note(S.editing?'Event updated':'Event created');S.editing=null;return load()}).catch(function(e){note(e.message,true)}).finally(function(){$('saveEventBtn').disabled=false})}
function statusArgs(e,status){return{p_event_id:e.id,p_title:e.title,p_slug:e.slug,p_description:e.description||'',p_ticket_price:Number(e.ticket_price),p_prize_amount:Number(e.prize_amount),p_prize_mode:e.prize_mode,p_max_tickets_per_user:e.max_tickets_per_user,p_white_ball_count:e.white_ball_count,p_white_ball_max:e.white_ball_max,p_bonus_ball_enabled:e.bonus_ball_enabled,p_bonus_ball_max:e.bonus_ball_max,p_opens_at:e.opens_at,p_cutoff_at:e.cutoff_at,p_draw_at:e.draw_at,p_status:status}}
function changeStatus(e,status){var msg=status==='cancelled'?'Cancel this event? Existing tickets remain recorded.':'Publish this event to the public site?';if(!confirm(msg))return;rpc('admin_update_lottery_event',statusArgs(e,status)).then(function(){note('Event '+status);return load()}).catch(function(x){note(x.message,true)})}
function deleteEvent(e){if(!confirm('Permanently delete this event? This is only allowed when it has no tickets.'))return;rpc('admin_delete_lottery_event',{p_event_id:e.id}).then(function(){note('Event deleted');return load()}).catch(function(x){note(x.message,true)})}
function runEvent(e){if(!confirm('Run the secure server draw now? You cannot choose the winning numbers.'))return;rpc('admin_run_lottery_event',{p_event_id:e.id}).then(function(){note('Event draw completed');return load()}).catch(function(x){note(x.message,true)})}

function openBalance(p){S.balanceUser=p;$('balanceTitle').textContent=p.display_name||'Player';$('balanceEmail').textContent=(p.email||'')+' · Current '+credits(p.balance);$('balanceInput').value=Number(p.balance||0);$('balanceNote').value='';$('balanceDialog').showModal()}
function saveBalance(ev){ev.preventDefault();if(!S.balanceUser)return;var amount=Number($('balanceInput').value);if(!Number.isFinite(amount)||amount<0){note('Balance must be zero or greater',true);return}rpc('admin_set_user_balance',{p_user_id:S.balanceUser.id,p_balance:amount,p_note:$('balanceNote').value.trim()||'Admin balance adjustment'}).then(function(){$('balanceDialog').close();note('Balance updated');return load()}).catch(function(e){note(e.message,true)})}

function bind(){document.querySelectorAll('.tabs button').forEach(function(b){b.onclick=function(){document.querySelectorAll('.tabs button').forEach(function(x){x.classList.remove('active')});document.querySelectorAll('.tab').forEach(function(x){x.classList.remove('active')});b.classList.add('active');$(b.dataset.tab).classList.add('active')}});$('retryBtn').onclick=boot;$('topCreate').onclick=openCreate;$('heroCreate').onclick=openCreate;$('createEventBtn').onclick=openCreate;$('refreshOverview').onclick=load;$('refreshAudit').onclick=load;$('eventStatusFilter').onchange=renderEvents;$('ticketEventFilter').onchange=renderTickets;$('ledgerUserFilter').onchange=renderLedger;$('closeEventModal').onclick=$('cancelEventModal').onclick=function(){$('eventDialog').close()};$('eventForm').onsubmit=saveEvent;$('fTitle').oninput=function(){if(!S.editing&&!$('fSlug').dataset.touched)$('fSlug').value=slugify(this.value)};$('fSlug').oninput=function(){this.dataset.touched='1'};$('fBonusEnabled').onchange=syncBonusField;$('cancelBalance').onclick=function(){$('balanceDialog').close()};$('balanceForm').onsubmit=saveBalance}

bind();boot();
})();