(function(){
'use strict';
if(window.PlatformGate)return;
var BASE='https://mwtlsnneooxmryondrex.supabase.co';
var KEY='sb_publishable_zfXYDH1qSZURp8bRHgnBrQ_7t7-3BMd';
var state={master:true,events:true,gameZone:true,slot:true,plinko:true,configured:{events:true,gameZone:true,slot:true,plinko:true}};
var resolveReady;
var ready=new Promise(function(resolve){resolveReady=resolve});
function api(){return fetch(BASE+'/rest/v1/rpc/get_platform_features',{method:'POST',headers:{apikey:KEY,'Content-Type':'application/json'},body:'{}'}).then(function(r){if(!r.ok)throw new Error('feature gate unavailable');return r.json()})}
function featureOn(name){if(name==='master')return !!state.master;if(name==='events')return !!state.events;if(name==='gameZone')return !!state.gameZone;if(name==='slot')return !!state.slot;if(name==='plinko')return !!state.plinko;return false}
function pausedCard(label){var s=document.createElement('section');s.className='platform-paused-card';s.innerHTML='<span>PLATFORM STATUS</span><h1>'+label+' is temporarily unavailable</h1><p>This section is currently paused by the administrator. Your account, profile, referrals and Support Points remain available.</p><div><a href="profile.html">Open Profile</a><a href="./">Home</a></div>';return s}
function hideLinks(){document.querySelectorAll('a[href="game-zone.html"],a[href="./#events"],a[href="#events"],a[href^="event.html"],a[href="slot.html"],a[href="plinko.html"]').forEach(function(a){var href=a.getAttribute('href')||'';if((href.indexOf('event')>=0||href.indexOf('#events')>=0)&&!state.events)a.hidden=true;else if(href.indexOf('slot.html')>=0&&!state.slot)a.hidden=true;else if(href.indexOf('plinko.html')>=0&&!state.plinko)a.hidden=true;else if(href.indexOf('game-zone.html')>=0&&!state.gameZone)a.hidden=true})}
function gateHome(){if(state.master)return;['.winner-marquee','.home-hero','.home-summary','.wallet-strip','.event-zone','.why-section','.how-section','.final-cta'].forEach(function(sel){document.querySelectorAll(sel).forEach(function(el){el.hidden=true})});var main=document.querySelector('main');if(main&&!document.querySelector('.platform-paused-card')){var card=pausedCard('Lottery & Game Zone');var nav=document.querySelector('.draw01-global-header');if(nav&&nav.nextSibling)nav.parentNode.insertBefore(card,nav.nextSibling);else main.insertBefore(card,main.firstChild)}}
function gatePage(){var path=(location.pathname.split('/').pop()||'index.html').toLowerCase();var need=null,label='This feature';if(path==='event.html'){need='events';label='Events'}else if(path==='game-zone.html'){need='gameZone';label='Game Zone'}else if(path==='slot.html'){need='slot';label='Slots'}else if(path==='plinko.html'){need='plinko';label='Plinko'}if(need&&!featureOn(need)){var main=document.querySelector('main');if(main)main.hidden=true;if(!document.querySelector('.platform-paused-card'))document.body.insertBefore(pausedCard(label),document.querySelector('.draw01-global-footer')||null)}if(path===''||path==='index.html')gateHome()}
function loadDeferred(){document.querySelectorAll('script[data-feature-src]').forEach(function(holder){var need=holder.getAttribute('data-feature')||'master';if(!featureOn(need))return;var s=document.createElement('script');s.src=holder.getAttribute('data-feature-src');if(holder.hasAttribute('data-module'))s.type='module';if(holder.hasAttribute('data-defer'))s.defer=true;document.body.appendChild(s)});document.querySelectorAll('link[data-feature-href]').forEach(function(holder){var need=holder.getAttribute('data-feature')||'master';if(!featureOn(need))return;var l=document.createElement('link');l.rel='stylesheet';l.href=holder.getAttribute('data-feature-href');document.head.appendChild(l)})}
function apply(){document.documentElement.dataset.platformMaster=state.master?'on':'off';hideLinks();gatePage();loadDeferred();document.dispatchEvent(new CustomEvent('platformfeaturesready',{detail:state}))}
function start(){api().then(function(data){if(data&&typeof data==='object')state=Object.assign({},state,data)}).catch(function(){}).finally(function(){apply();resolveReady(state)})}
window.PlatformGate={ready:ready,get:function(){return state},enabled:featureOn,refresh:function(){return api().then(function(d){state=Object.assign({},state,d||{});apply();return state})}};
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',start);else start();
})();