(function(){
'use strict';
if(window.PlatformGate)return;
var BASE='https://mwtlsnneooxmryondrex.supabase.co';
var KEY='sb_publishable_zfXYDH1qSZURp8bRHgnBrQ_7t7-3BMd';
var state={master:false,events:false,gameZone:false,slot:false,plinko:false,configured:{events:true,gameZone:true,slot:true,plinko:true}};
var resolveReady;
var ready=new Promise(function(resolve){resolveReady=resolve});
function api(){return fetch(BASE+'/rest/v1/rpc/get_platform_features',{method:'POST',headers:{apikey:KEY,'Content-Type':'application/json'},body:'{}'}).then(function(r){if(!r.ok)throw new Error('feature gate unavailable');return r.json()})}
function featureOn(name){if(name==='master')return !!state.master;if(name==='events')return !!state.events;if(name==='gameZone')return !!state.gameZone;if(name==='slot')return !!state.slot;if(name==='plinko')return !!state.plinko;return false}
function pausedCard(label){var s=document.createElement('section');s.className='platform-paused-card';s.innerHTML='<span>PLATFORM STATUS</span><h1>'+label+' is temporarily unavailable</h1><p>This section is currently paused by the administrator. Your account, profile, referrals and Love Points remain available.</p><div><a href="profile.html">Open Profile</a><a href="./">Home</a></div>';return s}
function hideLinks(){document.querySelectorAll('a[href="game-zone.html"],a[href="events.html"],a[href="./#events"],a[href="#events"],a[href^="event.html"],a[href="slot.html"],a[href="plinko.html"]').forEach(function(a){var href=a.getAttribute('href')||'',off=false;if(href==='events.html'||href.indexOf('event.html')>=0||href.indexOf('#events')>=0)off=!state.events;else if(href.indexOf('slot.html')>=0)off=!state.slot;else if(href.indexOf('plinko.html')>=0)off=!state.plinko;else if(href.indexOf('game-zone.html')>=0)off=!state.gameZone;a.hidden=off});var add=document.getElementById('d01AddCredit');if(add)add.hidden=!state.master}
function gateHome(){if(!state.events){['.winner-marquee','.home-summary','.event-zone'].forEach(function(sel){document.querySelectorAll(sel).forEach(function(el){el.hidden=true})})}if(state.master)return;['.home-hero','.wallet-strip','.why-section','.how-section','.final-cta'].forEach(function(sel){document.querySelectorAll(sel).forEach(function(el){el.hidden=true})});var main=document.querySelector('main');if(main&&!document.querySelector('.platform-paused-card'))main.insertBefore(pausedCard('Lottery & Game Zone'),main.firstChild)}
function gateGameCards(){var slot=document.getElementById('slotCard'),plinko=document.getElementById('plinkoCard'),count=document.getElementById('activeGames');if(slot)slot.hidden=!state.slot;if(plinko)plinko.hidden=!state.plinko;if(count)count.textContent=String((state.slot?1:0)+(state.plinko?1:0))}
function gatePage(){var path=(location.pathname.split('/').pop()||'index.html').toLowerCase();var need=null,label='This feature';if(path==='event.html'||path==='events.html'){need='events';label='Events'}else if(path==='game-zone.html'){need='gameZone';label='Game Zone'}else if(path==='slot.html'){need='slot';label='Slots'}else if(path==='plinko.html'){need='plinko';label='Plinko'}if(need&&!featureOn(need)){var main=document.querySelector('main');if(main)main.hidden=true;if(!document.querySelector('.platform-paused-card'))document.body.insertBefore(pausedCard(label),document.querySelector('.draw01-global-footer')||null)}else if(path==='game-zone.html'){gateGameCards()}if(path===''||path==='index.html')gateHome()}
function loadScriptsSequentially(list,index){if(index>=list.length)return Promise.resolve();var holder=list[index],need=holder.getAttribute('data-feature')||'master';if(!featureOn(need)||holder.dataset.featureLoaded==='1')return loadScriptsSequentially(list,index+1);holder.dataset.featureLoaded='1';return new Promise(function(resolve){var s=document.createElement('script');s.src=holder.getAttribute('data-feature-src');s.async=false;if(holder.hasAttribute('data-module'))s.type='module';s.onload=resolve;s.onerror=resolve;document.body.appendChild(s)}).then(function(){return loadScriptsSequentially(list,index+1)})}
function loadDeferred(){document.querySelectorAll('link[data-feature-href]').forEach(function(holder){var need=holder.getAttribute('data-feature')||'master';if(!featureOn(need)||holder.dataset.featureLoaded==='1')return;holder.dataset.featureLoaded='1';var l=document.createElement('link');l.rel='stylesheet';l.href=holder.getAttribute('data-feature-href');document.head.appendChild(l)});return loadScriptsSequentially(Array.prototype.slice.call(document.querySelectorAll('script[data-feature-src]')),0)}
function apply(){document.documentElement.dataset.platformMaster=state.master?'on':'off';hideLinks();gatePage();return loadDeferred().then(function(){gatePage();document.dispatchEvent(new CustomEvent('platformfeaturesready',{detail:state}))})}
function start(){api().then(function(data){if(data&&typeof data==='object')state=Object.assign({},state,data)}).catch(function(){}).finally(function(){apply().finally(function(){resolveReady(state)})})}
window.PlatformGate={ready:ready,get:function(){return state},enabled:featureOn,refresh:function(){return api().then(function(d){state=Object.assign({},state,d||{});return apply().then(function(){return state})})}};
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',start);else start();
})();