(function(){
'use strict';
var BASE='https://mwtlsnneooxmryondrex.supabase.co';
var KEY='sb_publishable_zfXYDH1qSZURp8bRHgnBrQ_7t7-3BMd';
var REF='mwtlsnneooxmryondrex';
var APP_URL='https://umar-vai.github.io/Lottery-/';
var ROWS=12;
var state={session:null,user:null,balance:null,bet:5,risk:'medium',busy:false,sound:true,game:null,audio:null};
function $(id){return document.getElementById(id)}
function unpack(x){if(!x)return null;if(x.access_token)return x;if(x.currentSession&&x.currentSession.access_token)return x.currentSession;if(x.session&&x.session.access_token)return x.session;if(x.data&&x.data.session&&x.data.session.access_token)return x.data.session;return null}
function readSession(){try{var keys=['sb-'+REF+'-auth-token'];for(var i=0;i<localStorage.length;i++){var k=localStorage.key(i);if(k&&k.indexOf(REF)>=0&&k.indexOf('auth')>=0&&keys.indexOf(k)<0)keys.push(k)}for(var j=0;j<keys.length;j++){var raw=localStorage.getItem(keys[j]);if(!raw)continue;try{var s=unpack(JSON.parse(raw));if(s)return s}catch(e){}}}catch(e){}return null}
function api(path,opt,token){opt=opt||{};var headers=Object.assign({apikey:KEY},opt.headers||{});if(token)headers.Authorization='Bearer '+token;if(opt.body)headers['Content-Type']='application/json';return fetch(BASE+path,Object.assign({},opt,{headers:headers})).then(function(r){return r.text().then(function(t){var d;try{d=t?JSON.parse(t):null}catch(e){d=t}if(!r.ok)throw new Error((d&&d.message)||(d&&d.error)||(typeof d==='string'&&d)||('HTTP '+r.status));return d})})}
function fmt(v){return Number(v||0).toLocaleString(undefined,{maximumFractionDigits:2})}
function pct(v){return (Number(v||0)*100).toFixed(2)+'%'}
function wait(ms){return new Promise(function(resolve){setTimeout(resolve,ms)})}
function nonce(){if(window.crypto&&crypto.randomUUID)return crypto.randomUUID();return 'xxxxxxxx-xxxx-4xxx-yxxx-xxxxxxxxxxxx'.replace(/[xy]/g,function(c){var r=Math.random()*16|0,v=c==='x'?r:(r&3|8);return v.toString(16)})}
function getAudio(){if(!state.sound)return null;try{if(!state.audio)state.audio=new (window.AudioContext||window.webkitAudioContext)();if(state.audio.state==='suspended')state.audio.resume();return state.audio}catch(e){return null}}
function tone(freq,duration,volume,delay,type){var ctx=getAudio();if(!ctx)return;var o=ctx.createOscillator(),g=ctx.createGain(),start=ctx.currentTime+(delay||0);o.type=type||'sine';o.frequency.setValueAtTime(freq,start);g.gain.setValueAtTime(.0001,start);g.gain.exponentialRampToValueAtTime(volume||.025,start+.008);g.gain.exponentialRampToValueAtTime(.0001,start+duration);o.connect(g);g.connect(ctx.destination);o.start(start);o.stop(start+duration+.03)}
function pegTone(i){tone(210+(i%6)*34,.055,.018,0,'triangle')}
function resultTone(kind){if(kind==='jackpot'){[330,440,550,660,880,990].forEach(function(f,i){tone(f,.22,.04,i*.075)})}else if(kind==='win'){[330,440,660].forEach(function(f,i){tone(f,.16,.03,i*.07)})}else if(kind==='partial'){tone(220,.1,.018,0);tone(270,.1,.018,.06)}else if(kind==='push'){tone(280,.1,.02,0);tone(350,.1,.02,.07)}else tone(130,.1,.012,0)}
function riskCfg(){var config=state.game&&state.game.config||{},m=config.riskModes||{};return m[state.risk]||null}
function nodeX(row,index){var grid=index+(ROWS-row)/2;return (5+(grid*(90/ROWS)))+'%'}
function pegY(row){return (12+(row*(68/(ROWS-1))))+'%'}
function bucketX(index){return (5+(index*(90/ROWS)))+'%'}
function renderBoard(){var layer=$('pegLayer');layer.innerHTML='';for(var r=0;r<ROWS;r++){for(var j=0;j<=r;j++){var p=document.createElement('i');p.className='peg';p.id='peg-'+r+'-'+j;p.style.left=nodeX(r,j);p.style.top=pegY(r);layer.appendChild(p)}}renderBuckets()}
function renderBuckets(){var cfg=riskCfg(),vals=cfg&&cfg.multipliers||[];var root=$('bucketLayer'),pay=$('paytableBuckets');root.innerHTML='';pay.innerHTML='';for(var i=0;i<=ROWS;i++){var mult=Number(vals[i]||0);var b=document.createElement('span');b.className='plinko-bucket'+(mult>=5?' high':'')+(mult===0?' zero':'');b.dataset.index=String(i);b.textContent=fmt(mult)+'×';root.appendChild(b);var x=document.createElement('span');x.textContent=fmt(mult)+'×';if(i===0||i===ROWS)x.classList.add('edge');pay.appendChild(x)}var max=vals.length?Math.max.apply(null,vals.map(Number)):0;$('maxMultiplier').textContent=fmt(max)+'×'}
function riskDescription(risk){if(risk==='low')return 'Smoother returns · lower volatility';if(risk==='high')return 'Rare extremes · highest volatility';return 'Balanced payout curve'}
function syncRiskUi(){var cfg=riskCfg();document.querySelectorAll('#riskOptions button').forEach(function(b){b.classList.toggle('active',b.dataset.risk===state.risk);b.disabled=state.busy});var pill=$('boardRiskPill');pill.className='risk-pill '+state.risk;pill.textContent=state.risk.toUpperCase();$('riskDescription').textContent=riskDescription(state.risk);$('riskMetricLabel').textContent=state.risk.charAt(0).toUpperCase()+state.risk.slice(1)+' risk';$('payoutTitle').textContent=state.risk.charAt(0).toUpperCase()+state.risk.slice(1)+' risk multipliers';if(cfg){$('rtpMetric').textContent=pct(cfg.rtp);$('edgeMetric').textContent=pct(cfg.houseEdge)}renderBuckets()}
function syncControls(){var signed=!!(state.session&&state.session.access_token),enough=state.balance==null?true:Number(state.balance)>=state.bet;$('dropBtn').hidden=!signed;$('plinkoLoginBtn').hidden=signed;$('dropBtn').disabled=state.busy||!enough;$('dropBtn').querySelector('small').textContent=enough?fmt(state.bet)+' CR':('Need '+fmt(state.bet)+' CR');$('betDisplay').textContent=fmt(state.bet)+' CR';document.querySelectorAll('#betOptions button').forEach(function(b){var v=Number(b.dataset.bet);b.classList.toggle('active',v===state.bet);b.disabled=state.busy||(signed&&state.balance!=null&&v>Number(state.balance))});document.querySelectorAll('#riskOptions button').forEach(function(b){b.disabled=state.busy})}
function setBalance(v){state.balance=Number(v||0);$('plinkoBalance').textContent=fmt(state.balance)+' CR';syncControls();if(window.GameZoneShell&&GameZoneShell.setBalance)GameZoneShell.setBalance(state.balance);else if(window.Draw01Shell&&Draw01Shell.setBalance)Draw01Shell.setBalance(state.balance)}
function setResult(kind,title,text){var el=$('dropResult');el.className='drop-result '+kind;el.querySelector('strong').textContent=title;el.querySelector('span').textContent=text}
function resetBoard(){document.querySelectorAll('.peg.hit').forEach(function(p){p.classList.remove('hit')});document.querySelectorAll('.plinko-bucket.hot').forEach(function(b){b.classList.remove('hot')});var ball=$('plinkoBall');ball.getAnimations().forEach(function(a){a.cancel()});ball.style.left='50%';ball.style.top='5%';ball.classList.remove('active')}
function animateTo(left,top,duration,easing){var ball=$('plinkoBall');var fromLeft=ball.style.left||'50%',fromTop=ball.style.top||'5%';var a=ball.animate([{left:fromLeft,top:fromTop,transform:'scale(1)'},{left:left,top:top,transform:'scale(.92)'},{left:left,top:top,transform:'scale(1)'}],{duration:duration,easing:easing||'cubic-bezier(.33,.7,.38,1)',fill:'forwards'});return a.finished.catch(function(){}).then(function(){ball.style.left=left;ball.style.top=top;a.cancel()})}
async function animatePath(path,landing){resetBoard();var ball=$('plinkoBall');ball.classList.add('active');await wait(80);var rights=0;for(var r=0;r<ROWS;r++){var peg=$('peg-'+r+'-'+rights);await animateTo(nodeX(r,rights),pegY(r),135+(r*3),'cubic-bezier(.25,.72,.45,1.15)');if(peg){peg.classList.add('hit');setTimeout((function(x){return function(){x.classList.remove('hit')}})(peg),180)}pegTone(r);try{if(navigator.vibrate)navigator.vibrate(8)}catch(e){}rights+=Number(path[r]||0);await wait(18)}await animateTo(bucketX(landing),'88.5%',240,'cubic-bezier(.25,.8,.3,1.2)');var bucket=document.querySelector('.plinko-bucket[data-index="'+landing+'"]');if(bucket)bucket.classList.add('hot');ball.classList.remove('active');try{if(navigator.vibrate)navigator.vibrate(28)}catch(e){}}
function confetti(kind){if(kind!=='win'&&kind!=='jackpot')return;var root=$('boardConfetti');root.innerHTML='';var colors=['#a8ff3e','#67e7ff','#ff65ba','#ffd75c','#ffffff'];var count=kind==='jackpot'?80:34;for(var i=0;i<count;i++){var x=document.createElement('i');x.style.left=(Math.random()*100)+'%';x.style.setProperty('--c',colors[i%colors.length]);x.style.setProperty('--d',(1+Math.random()*1.3)+'s');x.style.setProperty('--r',(Math.random()*180)+'deg');x.style.setProperty('--x',((Math.random()-.5)*190)+'px');x.style.animationDelay=(Math.random()*.18)+'s';root.appendChild(x)}setTimeout(function(){root.innerHTML=''},2800)}
function renderGame(g){state.game=g;if(!g)return;var steps=(g.bet_steps||[]).map(Number);if(steps.length){var root=$('betOptions');root.innerHTML='';steps.forEach(function(v){var b=document.createElement('button');b.type='button';b.dataset.bet=String(v);b.textContent=fmt(v);b.onclick=function(){if(state.busy)return;state.bet=v;syncControls()};root.appendChild(b)});if(steps.indexOf(state.bet)<0)state.bet=steps[0]}$('versionMetric').textContent='v'+g.version;renderBoard();syncRiskUi();syncControls()}
function loadGame(){return api('/rest/v1/games?select=slug,title,status,min_bet,max_bet,bet_steps,rtp,house_edge,version,config&slug=eq.neon-plinko&limit=1',{},null).then(function(rows){if(!rows||!rows[0])throw new Error('Plinko game unavailable');renderGame(rows[0])}).catch(function(e){setResult('loss','Game unavailable',e.message);$('dropBtn').disabled=true})}
function loadUser(){state.session=readSession();if(!state.session||!state.session.access_token){state.user=null;state.balance=null;$('plinkoBalance').textContent='Sign in';syncControls();renderHistory([]);return Promise.resolve()}var token=state.session.access_token;return api('/auth/v1/user',{},token).then(function(u){state.user=u;return api('/rest/v1/profiles?select=id,balance&id=eq.'+encodeURIComponent(u.id)+'&limit=1',{},token)}).then(function(rows){if(rows&&rows[0])setBalance(rows[0].balance);return loadHistory()}).catch(function(){state.session=null;state.user=null;state.balance=null;$('plinkoBalance').textContent='Sign in';syncControls();renderHistory([])})}
function loadHistory(){if(!state.session||!state.session.access_token)return Promise.resolve(renderHistory([]));return api('/rest/v1/plinko_drops?select=id,bet_amount,risk_mode,landing_index,multiplier,payout,net_change,balance_after,outcome_kind,created_at&order=created_at.desc&limit=15',{},state.session.access_token).then(renderHistory).catch(function(){renderHistory([])})}
function renderHistory(rows){var root=$('dropHistory');if(!state.session||!state.session.access_token){root.innerHTML='<div class="plinko-empty">Sign in to see your recent drops.</div>';return}if(!rows||!rows.length){root.innerHTML='<div class="plinko-empty">No drops yet. Your first result will appear here.</div>';return}root.innerHTML='';rows.forEach(function(x){var row=document.createElement('div');row.className='history-row';var net=Number(x.net_change||0),m=Number(x.multiplier||0);row.innerHTML='<div class="history-result"><strong>Bucket '+(Number(x.landing_index)+1)+' · '+fmt(m)+'×</strong><small>'+new Date(x.created_at).toLocaleString()+' · '+String(x.outcome_kind||'').toUpperCase()+'</small></div><div class="history-risk">'+String(x.risk_mode||'medium')+'</div><div class="history-cell">'+fmt(x.bet_amount)+' CR</div><div class="history-cell">'+fmt(x.payout)+' CR</div><div class="history-cell history-net '+(net>0?'positive':net<0?'negative':'')+'">'+(net>0?'+':'')+fmt(net)+' CR</div>';root.appendChild(row)})}
async function drop(){if(state.busy)return;if(!state.session||!state.session.access_token){login();return}if(state.balance==null||state.balance<state.bet){setResult('loss','Not enough credits','Choose a lower bet or add virtual credits.');return}state.busy=true;syncControls();syncRiskUi();setResult('neutral','Dropping…','Server is generating the 12-bounce path.');resetBoard();var result;try{result=await api('/rest/v1/rpc/drop_plinko',{method:'POST',body:JSON.stringify({p_bet_amount:state.bet,p_risk:state.risk,p_client_nonce:nonce()})},state.session.access_token);await animatePath(result.path||[],Number(result.landingIndex||0));setBalance(result.balanceAfter);var mult=Number(result.multiplier||0),payout=Number(result.payout||0),net=Number(result.net||0),kind=result.outcome||'loss';if(kind==='loss')setResult('loss','No return · '+fmt(mult)+'×','-'+fmt(state.bet)+' CR · Balance '+fmt(result.balanceAfter)+' CR');else if(kind==='partial')setResult('partial','Partial return · '+fmt(mult)+'×','Payout '+fmt(payout)+' CR · net '+fmt(net)+' CR');else if(kind==='push')setResult('neutral','Bet returned · 1×','Net 0 CR · Balance '+fmt(result.balanceAfter)+' CR');else if(kind==='jackpot')setResult('jackpot','MEGA DROP · '+fmt(mult)+'×','Payout '+fmt(payout)+' CR · net +'+fmt(net)+' CR');else setResult('win','WIN · '+fmt(mult)+'×','Payout '+fmt(payout)+' CR · net +'+fmt(net)+' CR');resultTone(kind);confetti(kind);if(kind==='jackpot'){try{if(navigator.vibrate)navigator.vibrate([80,40,80,40,140])}catch(e){}}await loadHistory()}catch(e){setResult('loss','Drop cancelled',e.message||'Could not complete this drop.');try{await loadUser()}catch(_){}}finally{state.busy=false;syncControls();syncRiskUi()}}
function login(){try{localStorage.setItem('gamezone_post_login_path','plinko.html')}catch(e){}var topLogin=$('loginBtn');if(topLogin){topLogin.click();return}location.href=BASE+'/auth/v1/authorize?provider=google&redirect_to='+encodeURIComponent(APP_URL)}
function bind(){document.querySelectorAll('#riskOptions button').forEach(function(b){b.onclick=function(){if(state.busy)return;state.risk=b.dataset.risk;syncRiskUi();syncControls()}});document.querySelectorAll('#betOptions button').forEach(function(b){b.onclick=function(){if(state.busy)return;state.bet=Number(b.dataset.bet);syncControls()}});$('dropBtn').onclick=drop;$('plinkoLoginBtn').onclick=login;$('refreshHistory').onclick=loadHistory;$('soundToggle').onclick=function(){state.sound=!state.sound;this.classList.toggle('off',!state.sound);this.setAttribute('aria-pressed',state.sound?'true':'false');this.textContent=state.sound?'♪ Sound':'♪ Muted';if(state.sound)tone(360,.08,.018,0)}}
function init(){bind();renderBoard();syncControls();loadGame().then(loadUser);setInterval(function(){if(!state.busy){var fresh=readSession();var had=!!(state.session&&state.session.access_token),has=!!(fresh&&fresh.access_token);if(had!==has)loadUser()}},4000)}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init);else init();
})();
