(function(){
'use strict';
var BASE='https://mwtlsnneooxmryondrex.supabase.co';
var KEY='sb_publishable_zfXYDH1qSZURp8bRHgnBrQ_7t7-3BMd';
var REF='mwtlsnneooxmryondrex';
var selected=[];var session=null;var user=null;
function $(id){return document.getElementById(id)}
function unpack(x){if(!x)return null;if(x.access_token)return x;if(x.currentSession&&x.currentSession.access_token)return x.currentSession;if(x.session&&x.session.access_token)return x.session;if(x.data&&x.data.session&&x.data.session.access_token)return x.data.session;return null}
function readSession(){try{var keys=['sb-'+REF+'-auth-token'];for(var i=0;i<localStorage.length;i++){var k=localStorage.key(i);if(k&&k.indexOf(REF)>=0&&k.indexOf('auth')>=0&&keys.indexOf(k)<0)keys.push(k)}for(var j=0;j<keys.length;j++){var raw=localStorage.getItem(keys[j]);if(!raw)continue;try{var s=unpack(JSON.parse(raw));if(s)return s}catch(e){}}}catch(e){}return null}
function api(path,opt){opt=opt||{};var h=Object.assign({apikey:KEY},opt.headers||{});if(session&&session.access_token)h.Authorization='Bearer '+session.access_token;if(opt.body)h['Content-Type']='application/json';return fetch(BASE+path,Object.assign({},opt,{headers:h})).then(function(r){return r.text().then(function(t){var d;try{d=t?JSON.parse(t):null}catch(e){d=t}if(!r.ok)throw new Error((d&&d.message)||(d&&d.error_description)||(d&&d.error)||('HTTP '+r.status));return d})})}
function esc(v){return String(v==null?'':v).replace(/[&<>"']/g,function(c){return {'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]})}
function paintNumbers(){var g=$('numberGrid');g.innerHTML='';for(var i=1;i<=20;i++){var b=document.createElement('button');b.type='button';b.textContent=i;b.dataset.n=i;if(selected.indexOf(i)>=0)b.className='selected';b.onclick=function(){toggle(Number(this.dataset.n))};g.appendChild(b)}$('selectedNumbers').textContent=selected.length?selected.slice().sort(function(a,b){return a-b}).join(', '):'None';$('buyTicket').disabled=selected.length!==5||!user}
function toggle(n){var p=selected.indexOf(n);if(p>=0)selected.splice(p,1);else if(selected.length<5)selected.push(n);paintNumbers()}
function quickPick(){var pool=[];for(var i=1;i<=20;i++)pool.push(i);selected=[];while(selected.length<5){var x=pool.splice(Math.floor(Math.random()*pool.length),1)[0];selected.push(x)}paintNumbers()}
function setNotice(msg,type){var n=$('notice');n.textContent=msg;n.className='notice'+(type?' '+type:'')}
function refresh(){session=readSession();if(!session){user=null;$('demoBalance').textContent='Sign in';paintNumbers();setNotice('Sign in with Google first. Ticket purchase uses Demo Credits only.');$('ticketList').innerHTML='<div class="empty">Sign in to see demo tickets.</div>';return Promise.resolve()}return api('/auth/v1/user').then(function(u){user=u;paintNumbers();return Promise.all([api('/rest/v1/demo_credit_wallets?select=balance&user_id=eq.'+encodeURIComponent(u.id)+'&limit=1'),api('/rest/v1/sandbox_demo_tickets?select=id,numbers,cost,balance_after,created_at&user_id=eq.'+encodeURIComponent(u.id)+'&order=created_at.desc&limit=20')])}).then(function(all){var w=all[0],t=all[1];$('demoBalance').textContent=Number(w&&w[0]?w[0].balance:0).toLocaleString(undefined,{maximumFractionDigits:2})+' Demo CR';$('ticketList').innerHTML=t&&t.length?t.map(function(x){return '<div class="ticket"><strong>'+esc((x.numbers||[]).join(' · '))+'</strong><span>Cost '+esc(x.cost)+' CR · Balance after '+esc(x.balance_after)+' · '+esc(new Date(x.created_at).toLocaleString())+'</span></div>'}).join(''):'<div class="empty">No demo tickets yet.</div>';return all}).catch(function(e){setNotice(e.message,'err')})}
function buy(){if(selected.length!==5||!user)return;var btn=$('buyTicket');btn.disabled=true;setNotice('Confirming sandbox ticket…');api('/rest/v1/rpc/buy_sandbox_demo_ticket',{method:'POST',body:JSON.stringify({p_numbers:selected.slice().sort(function(a,b){return a-b})})}).then(function(rows){var r=Array.isArray(rows)?rows[0]:rows;setNotice('Demo ticket confirmed. '+Number(r&&r.charged||10)+' Demo CR deducted.','ok');selected=[];paintNumbers();return refresh()}).catch(function(e){setNotice(e.message,'err');paintNumbers()})}
function install(){$('quickPick').onclick=quickPick;$('buyTicket').onclick=buy;paintNumbers();refresh();setInterval(function(){if(document.visibilityState!=='hidden')refresh()},4000)}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',install);else install();
})();