(function(){
'use strict';
var enhanced=false;
var BASE='https://mwtlsnneooxmryondrex.supabase.co';
var KEY='sb_publishable_zfXYDH1qSZURp8bRHgnBrQ_7t7-3BMd';
function $(id){return document.getElementById(id)}
function installSafetyStyle(){if(document.getElementById('gzNavV2Safety'))return;var s=document.createElement('style');s.id='gzNavV2Safety';s.textContent='.d01-account-v2[hidden]{display:none!important}.d01-credit-wrap[hidden]{display:none!important}.d01-admin-link[hidden]{display:none!important}.d01-login[hidden]{display:none!important}.d01-mobile-nav-admin[hidden]{display:none!important}';document.head.appendChild(s)}
function closeCredit(){var wrap=$('d01CreditWrap'),btn=$('d01CreditBtn');if(wrap)wrap.classList.remove('open');if(btn)btn.setAttribute('aria-expanded','false')}
function closeAccount(){var card=$('accountCard'),btn=$('d01AccountBtn');if(card)card.classList.remove('open');if(btn)btn.setAttribute('aria-expanded','false')}
function closeMobileNav(){var btn=$('d01MobileNavBtn'),drawer=$('d01MobileNavDrawer'),backdrop=$('d01MobileNavBackdrop');if(btn)btn.setAttribute('aria-expanded','false');if(drawer)drawer.classList.remove('open');if(backdrop)backdrop.classList.remove('open');document.documentElement.classList.remove('d01-mobile-menu-open')}
function toggleMobileNav(){var btn=$('d01MobileNavBtn'),drawer=$('d01MobileNavDrawer'),backdrop=$('d01MobileNavBackdrop');if(!btn||!drawer||!backdrop)return;var open=!drawer.classList.contains('open');closeCredit();closeAccount();drawer.classList.toggle('open',open);backdrop.classList.toggle('open',open);btn.setAttribute('aria-expanded',open?'true':'false');document.documentElement.classList.toggle('d01-mobile-menu-open',open)}
function syncMobileAdmin(){var source=$('adminNavLink'),mobile=$('d01MobileAdminLink');if(!mobile)return;mobile.hidden=!source||source.hidden}
function normalizeCreditText(){var el=$('d01CreditValue');if(!el)return;var text=String(el.textContent||'0').trim();var next=text.replace(/\s*credits?\s*$/i,'').trim()||'0';if(text!==next)el.textContent=next;var btn=$('d01CreditBtn');if(btn)btn.setAttribute('aria-label','Credit balance '+next)}
function loadAsset(tag,url,id){if(document.getElementById(id))return;var e=document.createElement(tag);e.id=id;if(tag==='link'){e.rel='stylesheet';e.href=url}else{e.src=url;e.defer=true}document.head.appendChild(e)}
function loadAdminControls(){if(!/ops-v4\.html$/i.test(location.pathname))return;loadAsset('link','platform-controls-admin.css?v=1','platformControlsCss');loadAsset('script','platform-controls-admin.js?v=4','platformControlsJs')}
function retargetEvents(){document.querySelectorAll('a[href="./#events"],a[href="#events"]').forEach(function(a){a.setAttribute('href','lotteries.html')})}
function applyPlatformNav(f){f=f||{};document.querySelectorAll('.d01-nav-link[href="lotteries.html"],.d01-nav-link[href="./#events"],.d01-footer-links a[href="lotteries.html"],.d01-footer-links a[href="./#events"],#d01MobileEventsLink').forEach(function(a){a.hidden=f.events===false});var add=$('d01AddCredit');if(add)add.hidden=f.master===false;syncMobileAdmin()}
function fetchPlatform(){return fetch(BASE+'/rest/v1/rpc/get_platform_features',{method:'POST',headers:{apikey:KEY,'Content-Type':'application/json'},body:'{}'}).then(function(r){if(!r.ok)throw new Error('feature state unavailable');return r.json()})}
function syncPlatform(){if(window.PlatformGate&&PlatformGate.ready){PlatformGate.ready.then(applyPlatformNav).catch(function(){})}else{fetchPlatform().then(applyPlatformNav).catch(function(){})}}
function installMobileNav(nav){if($('d01MobileNavBtn')){syncMobileAdmin();return}var actions=nav.querySelector('.d01-nav-right');if(!actions)return;var btn=document.createElement('button');btn.type='button';btn.id='d01MobileNavBtn';btn.className='d01-mobile-nav-toggle';btn.setAttribute('aria-label','Open navigation menu');btn.setAttribute('aria-controls','d01MobileNavDrawer');btn.setAttribute('aria-expanded','false');btn.innerHTML='<span></span><span></span><span></span>';actions.insertBefore(btn,actions.firstChild);
  var backdrop=document.createElement('button');backdrop.type='button';backdrop.id='d01MobileNavBackdrop';backdrop.className='d01-mobile-nav-backdrop';backdrop.setAttribute('aria-label','Close navigation menu');
  var drawer=document.createElement('aside');drawer.id='d01MobileNavDrawer';drawer.className='d01-mobile-nav-drawer';drawer.setAttribute('aria-label','Mobile navigation');drawer.innerHTML='<div class="d01-mobile-nav-head"><div><small>NAVIGATION</small><strong>Menu</strong></div><button type="button" class="d01-mobile-nav-close" id="d01MobileNavClose" aria-label="Close menu">×</button></div><nav class="d01-mobile-nav-links"><a id="d01MobileEventsLink" href="lotteries.html"><span>Lottery</span><small>সব লটারি দেখুন</small></a><a href="winners.html"><span>Winners</span><small>Winner hall ও result</small></a><a id="d01MobileAdminLink" class="d01-mobile-nav-admin" href="ops-v4.html" hidden><span>Admin Panel</span><small>Management controls</small></a></nav>';
  document.body.appendChild(backdrop);document.body.appendChild(drawer);btn.addEventListener('click',function(e){e.stopPropagation();toggleMobileNav()});backdrop.addEventListener('click',closeMobileNav);var close=$('d01MobileNavClose');if(close)close.addEventListener('click',closeMobileNav);drawer.querySelectorAll('a').forEach(function(a){a.addEventListener('click',closeMobileNav)});var source=$('adminNavLink');if(source&&window.MutationObserver)new MutationObserver(syncMobileAdmin).observe(source,{attributes:true,attributeFilter:['hidden','style','class']});syncMobileAdmin();window.addEventListener('resize',function(){if(window.innerWidth>560)closeMobileNav()},{passive:true})}
function enhance(){
  installSafetyStyle();var nav=document.querySelector('.draw01-global-nav');if(!nav)return false;retargetEvents();if(nav.dataset.navV2==='1'){installMobileNav(nav);syncPlatform();return true}nav.dataset.navV2='1';
  var center=nav.querySelector('.d01-nav-center');var profileNav=$('profileNavLink');if(profileNav)profileNav.remove();var live=nav.querySelector('.d01-live');if(live)live.remove();var admin=$('adminNavLink');if(admin&&center)center.appendChild(admin);
  var creditBtn=$('d01CreditBtn'),creditPopover=$('d01CreditPopover');if(creditBtn){var label=creditBtn.querySelector('.d01-credit-label');if(label)label.remove();creditBtn.setAttribute('title','Credits')}if(creditPopover){var intro=creditPopover.querySelector(':scope > span');if(intro)intro.remove();var duplicateProfile=creditPopover.querySelector('a[href="profile.html"]');if(duplicateProfile)duplicateProfile.remove()}
  var value=$('d01CreditValue');normalizeCreditText();if(value&&window.MutationObserver)new MutationObserver(normalizeCreditText).observe(value,{childList:true,characterData:true,subtree:true});
  var account=$('accountCard');if(account&&!account.dataset.accountV2){account.dataset.accountV2='1';account.classList.add('d01-account-v2');var avatar=$('userAvatar'),name=$('userName'),logout=$('logoutBtn');var toggle=document.createElement('button');toggle.type='button';toggle.id='d01AccountBtn';toggle.className='d01-account-toggle';toggle.setAttribute('aria-haspopup','true');toggle.setAttribute('aria-expanded','false');toggle.setAttribute('aria-label','Open account menu');if(avatar)toggle.appendChild(avatar);var pop=document.createElement('div');pop.id='d01AccountPopover';pop.className='d01-account-popover';pop.setAttribute('role','menu');var meta=document.createElement('div');meta.className='d01-account-meta';if(name)meta.appendChild(name);pop.appendChild(meta);var profile=document.createElement('a');profile.href='profile.html';profile.className='d01-account-menu-link';profile.textContent='My Profile & Referrals';profile.setAttribute('role','menuitem');pop.appendChild(profile);if(logout){logout.classList.add('d01-account-menu-logout');logout.setAttribute('role','menuitem');pop.appendChild(logout)}account.appendChild(toggle);account.appendChild(pop);toggle.addEventListener('click',function(e){e.stopPropagation();var willOpen=!account.classList.contains('open');closeCredit();closeMobileNav();account.classList.toggle('open',willOpen);toggle.setAttribute('aria-expanded',willOpen?'true':'false')});profile.addEventListener('click',closeAccount)}
  if(creditBtn)creditBtn.addEventListener('click',function(){closeAccount();closeMobileNav();setTimeout(normalizeCreditText,0)});document.addEventListener('click',function(e){var accountCard=$('accountCard');if(accountCard&&!accountCard.contains(e.target))closeAccount()});document.addEventListener('keydown',function(e){if(e.key==='Escape'){closeCredit();closeAccount();closeMobileNav()}});
  installMobileNav(nav);syncPlatform();loadAdminControls();return true;
}
function boot(){installSafetyStyle();loadAdminControls();if(enhance())enhanced=true;if(!enhanced){var tries=0,timer=setInterval(function(){tries++;if(enhance()||tries>20){clearInterval(timer);enhanced=true}},100)}}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot);else boot();
})();