(function(){
'use strict';
var BASE='https://mwtlsnneooxmryondrex.supabase.co';
var KEY='sb_publishable_zfXYDH1qSZURp8bRHgnBrQ_7t7-3BMd';
var REF='mwtlsnneooxmryondrex';
var APP_URL='https://umar-vai.github.io/Lottery-/';
var LABELS={cherry:'🍒',lemon:'🍋',bell:'🔔',bar:'BAR',seven:'7',diamond:'💎'};
var VISUAL=['🍒','🍋','🔔','BAR','7','💎'];
var state={session:null,user:null,balance:null,bet:5,busy:false,timers:[],sound:true,game:null,audio:null};
function $(id){return document.getElementById(id)}
function unpack(x){if(!x)return null;if(x.access_token)return x;if(x.currentSession&&x.currentSession.access_token)return x.currentSession;if(x.session&&x.session.access_token)return x.session;if(x.data&&x.data.session&&x.data.session.access_token)return x.data.session;return null}
function readSession(){try{var keys=['sb-'+REF+'-auth-token'];for(var i=0;i<localStorage.length;i++){var k=localStorage.key(i);if(k&&k.indexOf(REF)>=0&&k.indexOf('auth')>=0&&keys.indexOf(k)<0)keys.push(k)}for(var j=0;j<keys.length;j++){var raw=localStorage.getItem(keys[j]);if(!raw)continue;try{var s=unpack(JSON.parse(raw));if(s)return s}catch(e){}}}catch(e){}return null}
function api(path,opt,token){opt=opt||{};var headers=Object.assign({apikey:KEY},opt.headers||{});if(token)headers.Authorization='Bearer '+token;if(opt.body)headers['Content-Type']='application/json';return fetch(BASE+path,Object.assign({},opt,{headers:headers})).then(function(r){return r.text().then(function(t){var d;try{d=t?JSON.parse(t):null}catch(e){d=t}if(!r.ok)throw new Error((d&&d.message)||(d&&d.error)||(typeof d==='string'&&d)||('HTTP '+r.status));return d})})}
function fmt(v){return Number(v||0).toLocaleString(undefined,{maximumFractionDigits:2})}
function pct(v){return (Number(v||0)*100).toFixed(2)+'%'}
function wait(ms){return new Promise(function(resolve){setTimeout(resolve,ms)})}
function nonce(){if(window.crypto&&crypto.randomUUID)return crypto.randomUUID();return 'xxxxxxxx-xxxx-4xxx-yxxx-xxxxxxxxxxxx'.replace(/[xy]/g,function(c){var r=Math.random()*16|0,v=c==='x'?r:(r&3|8);return v.toString(16)})}
function setResult(kind,title,text){var el=$('spinResult');el.className='spin-result '+kind;el.querySelector('strong').textContent=title;el.querySelector('span').textContent=text}
function symbolLabel(k){return LABELS[k]||k||'—'}
function getAudio(){if(!state.sound)return null;try{if(!state.audio)state.audio=new (window.AudioContext||window.webkitAudioContext)();if(state.audio.state==='suspended')state.audio.resume();return state.audio}catch(e){return null}}
function tone(freq,duration,volume,delay){var ctx=getAudio();if(!ctx)return;var o=ctx.createOscillator(),g=ctx.createGain(),start=ctx.currentTime+(delay||0);o.type='sine';o.frequency.setValueAtTime(freq,start);g.gain.setValueAtTime(0.0001,start);g.gain.exponentialRampToValueAtTime(volume||.035,start+.01);g.gain.exponentialRampToValueAtTime(.0001,start+duration);o.connect(g);g.connect(ctx.destination);o.start(start);o.stop(start+duration+.03)}
function landSound(i){tone([190,240,310][i]||230,.09,.025,0)}
function winSound(kind){if(kind==='jackpot'){[330,440,550,660,880].forEach(function(f,i){tone(f,.22,.045,i*.09)})}else if(kind==='win'){[330,440,660].forEach(function(f,i){tone(f,.18,.035,i*.08)})}else if(kind==='push'){tone(260,.12,.025,0);tone(330,.12,.025,.08)}else{tone(135,.1,.015,0)}}
function startSpinVisual(){clearSpinVisual();$('slotMachine').classList.add('spinning');$('slotLever').classList.add('pulled');setTimeout(function(){$('slotLever').classList.remove('pulled')},420);for(var i=0;i<3;i++){(function(index){var reel=$('reelBox'+index),out=$('reel'+index);reel.classList.remove('land');reel.classList.add('spinning');state.timers[index]=setInterval(function(){out.textContent=VISUAL[Math.floor(Math.random()*VISUAL.length)]},55+index*11)})(i)}}
function clearSpinVisual(){state.timers.forEach(function(t){clearInterval(t)});state.timers=[];for(var i=0;i<3;i++)$('reelBox'+i).classList.remove('spinning')}
async function settle(symbols){for(var i=0;i<3;i++){await wait(310+i*55);if(state.timers[i])clearInterval(state.timers[i]);$('reel'+i).textContent=symbolLabel(symbols[i]);var box=$('reelBox'+i);box.classList.remove('spinning');box.classList.remove('land');void box.offsetWidth;box.classList.add('land');landSound(i);try{if(navigator.vibrate)navigator.vibrate(16)}catch(e){}}state.timers=[];$('slotMachine').classList.remove('spinning')}
function confetti(kind){if(kind!=='jackpot'&&kind!=='win')return;var root=$('confetti');root.innerHTML='';var colors=['#a8ff3e','#ff4aac','#ffd75c','#5fd8ff','#ffffff'];var count=kind==='jackpot'?70:32;for(var i=0;i<count;i++){var x=document.createElement('i');x.style.left=(Math.random()*100)+'%';x.style.setProperty('--c',colors[i%colors.length]);x.style.setProperty('--d',(1.1+Math.random()*1.5)+'s');x.style.setProperty('--r',(Math.random()*180)+'deg');x.style.setProperty('--x',((Math.random()-.5)*180)+'px');x.style.animationDelay=(Math.random()*.25)+'s';root.appendChild(x)}setTimeout(function(){root.innerHTML=''},3000)}
function flash(kind){var m=$('slotMachine');m.classList.remove('win-flash','jackpot-flash');if(kind==='win')m.classList.add('win-flash');if(kind==='jackpot')m.classList.add('jackpot-flash');setTimeout(function(){m.classList.remove('win-flash','jackpot-flash')},2700)}
function syncControls(){var signed=!!(state.session&&state.session.access_token),enough=state.balance==null?true:Number(state.balance)>=state.bet;$('spinBtn').hidden=!signed;$('slotLoginBtn').hidden=signed;$('spinBtn').disabled=state.busy||!enough;$('slotLever').disabled=state.busy||!signed||!enough;$('slotBetDisplay').textContent=fmt(state.bet)+' CR';$('spinBtn').querySelector('small').textContent=enough?fmt(state.bet)+' CR':('Need '+fmt(state.bet)+' CR');document.querySelectorAll('#betOptions button').forEach(function(b){var val=Number(b.dataset.bet);b.classList.toggle('active',val===state.bet);b.disabled=state.busy||(signed&&state.balance!=null&&val>Number(state.balance))})}
function setBalance(v){state.balance=Number(v||0);$('slotBalance').textContent=fmt(state.balance)+' CR';syncControls();if(window.GameZoneShell&&GameZoneShell.setBalance)GameZoneShell.setBalance(state.balance);else if(window.Draw01Shell&&Draw01Shell.setBalance)Draw01Shell.setBalance(state.balance)}
function renderGame(g){state.game=g;if(!g)return;$('rtpMetric').textContent=pct(g.rtp);$('edgeMetric').textContent=pct(g.house_edge);$('versionMetric').textContent='v'+g.version;var steps=(g.bet_steps||[]).map(Number);if(steps.length){var root=$('betOptions');root.innerHTML='';steps.forEach(function(v){var b=document.createElement('button');b.type='button';b.dataset.bet=String(v);b.textContent=fmt(v);if(v===state.bet)b.classList.add('active');b.onclick=function(){if(state.busy)return;state.bet=v;syncControls()};root.appendChild(b)});if(steps.indexOf(state.bet)<0)state.bet=steps[0]}syncControls()}
function loadGame(){return api('/rest/v1/games?select=slug,title,status,min_bet,max_bet,bet_steps,rtp,house_edge,version,config&slug=eq.classic-slot&limit=1',{},null).then(function(rows){if(!rows||!rows[0])throw new Error('Slot game unavailable');renderGame(rows[0])}).catch(function(e){setResult('loss','Game unavailable',e.message);$('spinBtn').disabled=true;$('slotLever').disabled=true})}
function loadUser(){state.session=readSession();if(!state.session||!state.session.access_token){state.user=null;state.balance=null;$('slotBalance').textContent='Sign in';syncControls();renderHistory([]);return Promise.resolve()}var token=state.session.access_token;return api('/auth/v1/user',{},token).then(function(u){state.user=u;return api('/rest/v1/profiles?select=id,balance&id=eq.'+encodeURIComponent(u.id)+'&limit=1',{},token)}).then(function(rows){if(rows&&rows[0])setBalance(rows[0].balance);return loadHistory()}).catch(function(){state.session=null;state.user=null;state.balance=null;$('slotBalance').textContent='Sign in';syncControls();renderHistory([])})}
function loadHistory(){if(!state.session||!state.session.access_token)return Promise.resolve(renderHistory([]));return api('/rest/v1/slot_spins?select=id,bet_amount,reel_1,reel_2,reel_3,multiplier,payout,net_change,balance_after,outcome_kind,created_at&order=created_at.desc&limit=15',{},state.session.access_token).then(renderHistory).catch(function(){renderHistory([])})}
function renderHistory(rows){var root=$('spinHistory');if(!state.session||!state.session.access_token){root.innerHTML='<div class="slot-empty">Sign in to see your recent spins.</div>';return}if(!rows||!rows.length){root.innerHTML='<div class="slot-empty">No spins yet. Your first result will appear here.</div>';return}root.innerHTML='';rows.forEach(function(x){var r=document.createElement('div');r.className='history-row';var net=Number(x.net_change||0),kind=x.outcome_kind||'loss';r.innerHTML='<div class="history-meta"><div class="history-symbols"><span>'+symbolLabel(x.reel_1)+'</span><span>'+symbolLabel(x.reel_2)+'</span><span>'+symbolLabel(x.reel_3)+'</span></div><small>'+new Date(x.created_at).toLocaleString()+' · '+kind.toUpperCase()+'</small></div><div class="history-bet">'+fmt(x.bet_amount)+' CR</div><div class="history-payout '+(Number(x.payout)>Number(x.bet_amount)?'win':'')+'">'+fmt(x.payout)+' CR</div><div class="history-net '+(net>0?'positive':net<0?'negative':'')+'">'+(net>0?'+':'')+fmt(net)+' CR</div>';root.appendChild(r)})}
async function spin(){if(state.busy)return;if(!state.session||!state.session.access_token){login();return}if(state.balance==null||state.balance<state.bet){setResult('loss','Not enough credits','Choose a lower bet or add virtual credits.');return}state.busy=true;syncControls();setResult('neutral','Spinning…','Server is generating the final result.');startSpinVisual();var started=Date.now(),result=null;try{result=await api('/rest/v1/rpc/spin_slot',{method:'POST',body:JSON.stringify({p_bet_amount:state.bet,p_client_nonce:nonce()})},state.session.access_token);var remaining=Math.max(0,1050-(Date.now()-started));if(remaining)await wait(remaining);await settle(result.symbols||[]);setBalance(result.balanceAfter);var payout=Number(result.payout||0),net=Number(result.net||0),mult=Number(result.multiplier||0),kind=result.outcome||'loss';if(kind==='loss')setResult('loss','No match','-'+fmt(state.bet)+' CR · Balance '+fmt(result.balanceAfter)+' CR');else if(kind==='push')setResult('push','Pair — bet returned','1× payout · net 0 CR');else if(kind==='jackpot')setResult('jackpot','JACKPOT · '+fmt(mult)+'×','Payout '+fmt(payout)+' CR · net +'+fmt(net)+' CR');else setResult('win','WIN · '+fmt(mult)+'×','Payout '+fmt(payout)+' CR · net +'+fmt(net)+' CR');winSound(kind);flash(kind);confetti(kind);if(kind==='jackpot'){try{if(navigator.vibrate)navigator.vibrate([70,45,70,45,120])}catch(e){}}await loadHistory()}catch(e){clearSpinVisual();setResult('loss','Spin cancelled',e.message||'Could not complete this spin.');try{await loadUser()}catch(_){} }finally{state.busy=false;syncControls()}}
function login(){try{localStorage.setItem('gamezone_post_login_path','slot.html')}catch(e){}var topLogin=$('loginBtn');if(topLogin){topLogin.click();return}location.href=BASE+'/auth/v1/authorize?provider=google&redirect_to='+encodeURIComponent(APP_URL)}
function bind(){document.querySelectorAll('#betOptions button').forEach(function(b){b.onclick=function(){if(state.busy)return;state.bet=Number(b.dataset.bet);syncControls()}});$('spinBtn').onclick=spin;$('slotLever').onclick=spin;$('slotLoginBtn').onclick=login;$('refreshHistory').onclick=function(){loadHistory()};$('soundToggle').onclick=function(){state.sound=!state.sound;this.classList.toggle('off',!state.sound);this.setAttribute('aria-pressed',state.sound?'true':'false');this.textContent=state.sound?'♪ Sound':'♪ Muted';if(state.sound)tone(330,.08,.02,0)}}
function init(){bind();syncControls();loadGame();loadUser();setInterval(function(){if(!state.busy){var fresh=readSession();var had=!!(state.session&&state.session.access_token),has=!!(fresh&&fresh.access_token);if(had!==has)loadUser()}},4000)}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init);else init();
})();
