(function(){
'use strict';
var BASE='https://mwtlsnneooxmryondrex.supabase.co';
var KEY='sb_publishable_zfXYDH1qSZURp8bRHgnBrQ_7t7-3BMd';
var REF='mwtlsnneooxmryondrex';
var BKASH_NUMBER='01580537956';
var S={session:null,user:null,claims:[],requests:[],timer:null};
function $(id){return document.getElementById(id)}
function esc(v){return String(v==null?'':v).replace(/[&<>"']/g,function(c){return {'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]})}
function unpack(x){if(!x)return null;if(x.access_token)return x;if(x.currentSession&&x.currentSession.access_token)return x.currentSession;if(x.session&&x.session.access_token)return x.session;if(x.data&&x.data.session&&x.data.session.access_token)return x.data.session;return null}
function readSession(){try{var keys=['sb-'+REF+'-auth-token'];for(var i=0;i<localStorage.length;i++){var k=localStorage.key(i);if(k&&k.indexOf(REF)>=0&&k.indexOf('auth')>=0&&keys.indexOf(k)<0)keys.push(k)}for(var j=0;j<keys.length;j++){var raw=localStorage.getItem(keys[j]);if(!raw)continue;try{var s=unpack(JSON.parse(raw));if(s)return s}catch(e){}}}catch(e){}return null}
function req(path,opt){opt=opt||{};var h=Object.assign({apikey:KEY},opt.headers||{});if(S.session&&S.session.access_token)h.Authorization='Bearer '+S.session.access_token;if(opt.body)h['Content-Type']='application/json';return fetch(BASE+path,Object.assign({},opt,{headers:h})).then(function(r){return r.text().then(function(t){var d;try{d=t?JSON.parse(t):null}catch(e){d=t}if(!r.ok)throw new Error((d&&d.error)||(d&&d.message)||(d&&d.details)||('HTTP '+r.status));return d})})}
function fmt(v){return v?new Date(v).toLocaleString('bn-BD',{year:'numeric',month:'short',day:'numeric',hour:'numeric',minute:'2-digit'}):'—'}
function lp(v){return Number(v||0).toLocaleString('bn-BD',{maximumFractionDigits:2})+' LP'}
function normalizeLandPointLabels(root){
  try{
    var host=root||document.body;if(!host)return;var walker=document.createTreeWalker(host,NodeFilter.SHOW_TEXT),node;
    while((node=walker.nextNode())){
      var before=node.nodeValue||'';if(!/Support Point|\bSP\b/i.test(before))continue;
      var after=before.replace(/Support Points/gi,'Land Points').replace(/Support Point/gi,'Land Point').replace(/\bSP\b/g,'LP');
      if(after!==before)node.nodeValue=after;
    }
  }catch(e){}
}
function install(){
  normalizeLandPointLabels();
  setTimeout(normalizeLandPointLabels,500);setTimeout(normalizeLandPointLabels,2000);setTimeout(normalizeLandPointLabels,6000);
  if($('d01SupportCenter'))return;
  document.body.insertAdjacentHTML('beforeend','<div id="d01SupportCenter" class="d01-support-center" hidden><section class="sp-shell" role="dialog" aria-modal="true" aria-labelledby="spTitle"><header class="sp-head"><div><small>ভালোবাসা দিন</small><h2 id="spTitle">ল্যান্ড পয়েন্ট (LP)</h2><p>আপনার ভালোবাসার সহায়তা পাঠান। যাচাইকৃত লেনদেন সার্ভারে পৌঁছালে LP স্বয়ংক্রিয়ভাবে যোগ হয়ে যাবে।</p></div><button id="spClose" class="sp-close" type="button" aria-label="বন্ধ করুন">×</button></header><div class="sp-body"><div class="sp-summary"><article class="sp-balance"><span>আপনার ল্যান্ড পয়েন্ট ব্যালেন্স</span><strong id="spBalance">০ LP</strong><small>৳১ = ১ LP</small></article><article class="sp-rules"><strong>ড্র ক্রেডিট থেকে সম্পূর্ণ আলাদা</strong><p>LP দিয়ে কোনো লটারির টিকিট কেনা, জেতার সম্ভাবনা বাড়ানো, পুরস্কারের যোগ্যতা তৈরি, ক্যাশে রূপান্তর বা টাকা উত্তোলন করা যায় না। এটি শুধু আপনার ভালোবাসার সহায়তার হিসাব।</p></article></div><div class="sp-grid"><article class="sp-panel"><h3>বিকাশে ভালোবাসা পাঠান</h3><p>প্রথমে নিচের বিকাশ নম্বরে টাকা পাঠান। এরপর যে নম্বর থেকে পাঠিয়েছেন এবং বিকাশের TrxID লিখে একবার জমা দিন। লেনদেনটি সিস্টেমে পৌঁছালে যাচাই স্বয়ংক্রিয়ভাবে সম্পন্ন হবে।</p><div class="sp-bkash-target"><span>যে বিকাশ নম্বরে পাঠাবেন</span><strong>'+BKASH_NUMBER+'</strong><small>টাকা পাঠানোর পর Sender Number ও TrxID নিচে দিন।</small><button id="spCopyNumber" type="button">নম্বর কপি করুন</button></div><form id="spForm"><label class="sp-label"><span>যে বিকাশ নম্বর থেকে পাঠিয়েছেন</span><input id="spSender" inputmode="tel" autocomplete="off" placeholder="01XXXXXXXXX" required></label><label class="sp-label"><span>ট্রানজ্যাকশন আইডি (TrxID)</span><input id="spTrx" autocomplete="off" autocapitalize="characters" placeholder="যেমন: BCD123XYZ" required></label><label class="sp-check"><input id="spTerms" type="checkbox"><span>আমি বুঝেছি, এই LP শুধু ভালোবাসার সহায়তার রেকর্ড। এটি কোনো ড্র, টিকিট, জেতার সম্ভাবনা বা পুরস্কারের জন্য ব্যবহার করা যাবে না।</span></label><button id="spSubmit" class="sp-submit" type="submit">জমা দিন ও যাচাই করুন</button><div id="spMsg" class="sp-msg"></div></form><div class="sp-help">লেনদেনটি সঙ্গে সঙ্গে না মিললে আপনার তথ্য অপেক্ষমাণ থাকবে। ম্যাচিং ট্রানজ্যাকশন সার্ভারে আসলেই সিস্টেম নিজে থেকে যাচাই করে LP যোগ করবে—আবার Verify চাপতে হবে না।</div></article><article class="sp-panel"><h3>ভালোবাসার ইতিহাস</h3><p>আপনার অপেক্ষমাণ ও সম্পন্ন হওয়া লেনদেনগুলো এখানে দেখা যাবে।</p><div id="spHistory" class="sp-history"><div class="sp-empty">লোড হচ্ছে…</div></div></article></div></div></section></div>');
  $('spClose').onclick=close;var c=$('d01SupportCenter');c.addEventListener('click',function(e){if(e.target===c)close()});document.addEventListener('keydown',function(e){if(e.key==='Escape'&&!c.hidden)close()});$('spForm').onsubmit=claim;
  $('spCopyNumber').onclick=function(){var b=this;if(navigator.clipboard&&navigator.clipboard.writeText){navigator.clipboard.writeText(BKASH_NUMBER).then(function(){b.textContent='কপি হয়েছে ✓';setTimeout(function(){b.textContent='নম্বর কপি করুন'},1500)})}else{prompt('বিকাশ নম্বর',BKASH_NUMBER)}};
}
function msg(t,err){var n=$('spMsg');if(!n)return;n.textContent=t||'';n.className='sp-msg'+(err?' err':'')}
function renderHistory(){var r=$('spHistory');if(!r)return;var settled=S.claims.map(function(x){return {kind:'settled',created_at:x.created_at,points:x.points,amount:x.amount_bdt}});var pending=S.requests.filter(function(x){return x.status!=='settled'}).map(function(x){return {kind:x.status,created_at:x.created_at,trx:x.trx_id,last4:x.sender_last4}});var all=pending.concat(settled).sort(function(a,b){return new Date(b.created_at)-new Date(a.created_at)});if(!all.length){r.innerHTML='<div class="sp-empty">এখনও কোনো ভালোবাসার লেনদেন নেই।</div>';return}r.innerHTML=all.map(function(x){if(x.kind==='settled')return '<article class="sp-row"><div><strong>+'+esc(lp(x.points))+'</strong><span>'+esc(fmt(x.created_at))+' · সম্পন্ন</span></div><b>৳'+esc(Number(x.amount||0).toLocaleString('bn-BD',{maximumFractionDigits:2}))+'</b></article>';var label=x.kind==='pending'?'অপেক্ষমাণ':'মেয়াদ শেষ';return '<article class="sp-row"><div><strong>'+label+' · TrxID '+esc(x.trx||'')+'</strong><span>'+esc(fmt(x.created_at))+' · প্রেরক ****'+esc(x.last4||'')+'</span></div><b>'+(x.kind==='pending'?'মিল পাওয়ার অপেক্ষায়':'মেয়াদ শেষ')+'</b></article>'}).join('')}
function load(){S.session=readSession();if(!S.session){msg('আগে Google দিয়ে সাইন ইন করুন।',true);if($('spBalance'))$('spBalance').textContent='সাইন ইন প্রয়োজন';return Promise.resolve()}return req('/auth/v1/user').then(function(u){S.user=u;return Promise.all([req('/rest/v1/support_wallets?select=balance&user_id=eq.'+encodeURIComponent(u.id)+'&limit=1'),req('/rest/v1/support_point_claims?select=id,amount_bdt,points,balance_after,created_at&user_id=eq.'+encodeURIComponent(u.id)+'&order=created_at.desc&limit=30'),req('/rest/v1/support_claim_requests?select=id,trx_id,sender_last4,status,amount_bdt,points,created_at,settled_at,expires_at&user_id=eq.'+encodeURIComponent(u.id)+'&order=created_at.desc&limit=30')])}).then(function(x){var bal=x[0]&&x[0][0]?x[0][0].balance:0;S.claims=x[1]||[];S.requests=x[2]||[];$('spBalance').textContent=lp(bal);renderHistory()}).catch(function(e){console.warn('LP load failed',e);msg('এই মুহূর্তে LP তথ্য লোড করা যাচ্ছে না। একটু পরে আবার চেষ্টা করুন।',true)})}
function claim(e){e.preventDefault();S.session=readSession();if(!S.session){msg('আগে সাইন ইন করুন।',true);return}var sender=$('spSender').value.trim(),trx=$('spTrx').value.trim().toUpperCase();if(!/^01\d{9}$/.test(sender)){msg('সঠিক ১১ সংখ্যার বিকাশ নম্বর দিন।',true);return}if(!/^[A-Z0-9]{6,32}$/.test(trx)){msg('সঠিক TrxID দিন।',true);return}if(!$('spTerms').checked){msg('LP-এর শর্তটি নিশ্চিত করুন।',true);return}var b=$('spSubmit');b.disabled=true;b.textContent='যাচাই হচ্ছে…';msg('');req('/functions/v1/claim-support-points',{method:'POST',body:JSON.stringify({senderNumber:sender,trxId:trx,acceptedTerms:true})}).then(function(d){$('spSender').value='';$('spTrx').value='';$('spTerms').checked=false;if(d.status==='pending')msg('তথ্য জমা হয়েছে। মিল পাওয়া মাত্র LP স্বয়ংক্রিয়ভাবে যোগ হবে।');else msg('যাচাই সম্পন্ন। আপনার ব্যালেন্সে '+lp(d.points||d.amount||0)+' যোগ হয়েছে।');return load()}).catch(function(err){console.warn('LP claim failed',err);msg('যাচাই করা যায়নি। Sender Number ও TrxID ঠিক আছে কি না দেখে আবার চেষ্টা করুন।',true)}).finally(function(){b.disabled=false;b.textContent='জমা দিন ও যাচাই করুন'})}
function open(){install();normalizeLandPointLabels();var c=$('d01SupportCenter');c.hidden=false;document.body.style.overflow='hidden';load();clearInterval(S.timer);S.timer=setInterval(function(){if(!c.hidden)load()},6000)}
function close(){var c=$('d01SupportCenter');if(c)c.hidden=true;document.body.style.overflow='';clearInterval(S.timer);S.timer=null}
window.LandPointsUI={normalize:normalizeLandPointLabels};
window.Draw01SupportCenter={open:open,close:close,refresh:load};
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',install);else install();
})();