const SUPABASE_URL = Deno.env.get('SUPABASE_URL')!;
const SERVICE_KEY = Deno.env.get('SUPABASE_SERVICE_ROLE_KEY')!;
const BINANCE_KEY = Deno.env.get('BINANCE_PAY_API_KEY') || '';
const BINANCE_SECRET = Deno.env.get('BINANCE_PAY_SECRET_KEY') || '';
const BINANCE_HOST = 'https://bpay.binanceapi.com';
const APP_URL = 'https://umar-vai.github.io/Lottery-/';
const encoder = new TextEncoder();

function cors(req: Request) {
  const origin = req.headers.get('origin') || '';
  const allowed = origin === 'https://umar-vai.github.io' || origin.startsWith('http://localhost:');
  return {
    'Access-Control-Allow-Origin': allowed ? origin : 'https://umar-vai.github.io',
    'Access-Control-Allow-Headers': 'authorization,content-type,apikey',
    'Access-Control-Allow-Methods': 'POST,OPTIONS',
    'Vary': 'Origin',
  };
}
function json(req: Request, data: unknown, status = 200) { return new Response(JSON.stringify(data), { status, headers: { ...cors(req), 'content-type': 'application/json' } }); }
async function currentUser(req: Request) { const auth=req.headers.get('authorization')||''; if(!auth.startsWith('Bearer ')) throw new Error('Authentication required'); const r=await fetch(`${SUPABASE_URL}/auth/v1/user`,{headers:{apikey:SERVICE_KEY,Authorization:auth}}); if(!r.ok) throw new Error('Invalid session'); return await r.json(); }
async function db(path:string,init:RequestInit={}){const headers={apikey:SERVICE_KEY,Authorization:`Bearer ${SERVICE_KEY}`,'content-type':'application/json',...(init.headers||{})} as Record<string,string>;const r=await fetch(`${SUPABASE_URL}/rest/v1/${path}`,{...init,headers});const text=await r.text();let data:any=null;try{data=text?JSON.parse(text):null}catch{data=text}if(!r.ok)throw new Error(data?.message||data?.details||String(data)||'Database error');return data}
function randomAlphaNum(length:number){const chars='ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789';const bytes=crypto.getRandomValues(new Uint8Array(length));return Array.from(bytes,b=>chars[b%chars.length]).join('')}
function merchantTradeNo(){return (`LP${Date.now()}${randomAlphaNum(12)}`).slice(0,32)}
async function hmacSha512Hex(secret:string,payload:string){const key=await crypto.subtle.importKey('raw',encoder.encode(secret),{name:'HMAC',hash:'SHA-512'},false,['sign']);const sig=await crypto.subtle.sign('HMAC',key,encoder.encode(payload));return Array.from(new Uint8Array(sig)).map(x=>x.toString(16).padStart(2,'0')).join('').toUpperCase()}
async function binanceRequest(path:string,body:Record<string,unknown>){const timestamp=String(Date.now());const nonce=randomAlphaNum(32);const raw=JSON.stringify(body);const signature=await hmacSha512Hex(BINANCE_SECRET,`${timestamp}\n${nonce}\n${raw}\n`);const r=await fetch(`${BINANCE_HOST}${path}`,{method:'POST',headers:{'content-type':'application/json','BinancePay-Timestamp':timestamp,'BinancePay-Nonce':nonce,'BinancePay-Certificate-SN':BINANCE_KEY,'BinancePay-Signature':signature},body:raw});const text=await r.text();let data:any;try{data=text?JSON.parse(text):null}catch{data={status:'FAIL',errorMessage:text}}if(!r.ok||data?.status!=='SUCCESS'||!data?.data)throw new Error(data?.errorMessage||data?.code||`Binance Pay HTTP ${r.status}`);return data}

Deno.serve(async(req:Request)=>{try{if(req.method==='OPTIONS')return new Response('',{headers:cors(req)});if(req.method!=='POST')return json(req,{error:'POST required'},405);const user=await currentUser(req);const settingsRows=await db('love_point_payment_providers?provider=eq.binance_pay&select=provider,display_name,public_visible,enabled,order_currency,lp_per_currency_unit,min_lp,max_lp&limit=1');const settings=settingsRows?.[0];if(!settings||settings.enabled!==true)return json(req,{error:'Binance Pay is not enabled yet',code:'BINANCE_PAY_DISABLED'},503);if(!BINANCE_KEY||!BINANCE_SECRET)return json(req,{error:'Binance Pay merchant credentials are not configured',code:'BINANCE_PAY_NOT_CONFIGURED'},503);const body=await req.json();const lpAmount=Number(body?.lpAmount||0);const minLp=Number(settings.min_lp||0);const maxLp=Number(settings.max_lp||0);const lpPerUnit=Number(settings.lp_per_currency_unit||0);if(!Number.isFinite(lpAmount)||lpAmount<minLp||(maxLp>0&&lpAmount>maxLp))return json(req,{error:`Love Points must be between ${minLp} and ${maxLp}`},400);if(!Number.isFinite(lpPerUnit)||lpPerUnit<=0)return json(req,{error:'Binance Pay LP conversion rate is not configured',code:'BINANCE_PAY_RATE_MISSING'},503);const currency=String(settings.order_currency||'USDT').toUpperCase();const orderAmount=Number((lpAmount/lpPerUnit).toFixed(8));if(!Number.isFinite(orderAmount)||orderAmount<0.00000001)return json(req,{error:'Calculated Binance Pay amount is too small'},400);const tradeNo=merchantTradeNo();const orderBody={env:{terminalType:'WEB'},merchantTradeNo:tradeNo,orderAmount,currency,description:`${lpAmount} Love Points support`,goodsDetails:[{goodsType:'02',goodsCategory:'Z000',referenceGoodsId:'LOVEPOINTS',goodsName:'Love Points Support',goodsDetail:`${lpAmount} Love Points`}],returnUrl:`${APP_URL}?binancePay=success`,cancelUrl:`${APP_URL}?binancePay=cancel`,webhookUrl:`${SUPABASE_URL}/functions/v1/binance-pay-webhook`};const created=await binanceRequest('/binancepay/openapi/v3/order',orderBody);const d=created.data;await db('binance_pay_orders',{method:'POST',headers:{Prefer:'return=minimal'},body:JSON.stringify({user_id:user.id,merchant_trade_no:tradeNo,prepay_id:String(d.prepayId||''),lp_amount:lpAmount,order_amount:Number(d.totalFee||orderAmount),order_currency:String(d.currency||currency).toUpperCase(),status:'pending',checkout_url:d.checkoutUrl||null,qrcode_link:d.qrcodeLink||null,deeplink:d.deeplink||d.universalUrl||null,expire_time_ms:d.expireTime?Number(d.expireTime):null,raw_create:created})});return json(req,{ok:true,merchantTradeNo:tradeNo,prepayId:d.prepayId,lpAmount,orderAmount:Number(d.totalFee||orderAmount),currency:String(d.currency||currency),checkoutUrl:d.checkoutUrl,qrcodeLink:d.qrcodeLink,deeplink:d.deeplink,universalUrl:d.universalUrl,expireTime:d.expireTime})}catch(e){const message=e instanceof Error?e.message:String(e);return json(req,{error:message},/Authentication|Invalid session/.test(message)?401:400)}});